Community Patch/Core Files/Core Changes/TextChanges.sql
The vanilla text still describes Exploration as being the name of the
policy that reveals the hidden sites.
=> Pedia Entry for Hidden antiguity sites

Community Patch/Community Patch.civ5proj, Community Patch/Core Files/Core Tables/CoreTableAdditions1HH.xml, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.h, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/CvTradeClasses.h, CvGameCoreDLL_Expansion2/HHMods.h
See HHMods.h, which directs you to the preprocessor define HH_MOD_API_TRADEROUTE_MODIFIERS
No tooltips
=> Policy_InternationalRouteYieldModifiers, no tooltips

Community Patch/Core Files/CoreLua/CityEventsInfo.lua, Community Patch/Core Files/CoreLua/CityRecentEventsInfo.lua, Community Patch/Core Files/CoreLua/PlayerEventsInfo.lua, Community Patch/Core Files/CoreLua/RecentEventsInfo.lua
Hi, I am new to Civ5 mod, 
When I play, I found occupationally if i open/close event overview panel and switch sub panel inside (with EUI), the next turn button can be locked, (no effect when click, but still clickable) , i can reproduce this issue very easily by repeating those operations.
after taking look into the lua file, I think I may found the cause, in those 4 sub panel lua files, 
PlayerEventsInfo.lua, RecentEventsInfo.lua, CityEventsInfo.lua,  CityRecentEventsInfo.lua
they all have ShowHideHandler, and do UI.incTurnTimerSemaphore(); on show and UI.decTurnTimerSemaphore(); on hide
and in EventOverview.lua, it saves m_CurrentPanel as state and call setHide() method for all panels, on close it looks like not calling subpanel SetHide(), and i am not sure how setHide() works …
=> fix event overview panel lock UI next turn issue

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyAI.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvRandom.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
Changes for upcoming civ compatibility I'm working on. Literally first time editing DLL codes, hopefully it goes well....
- Allows you to increase (or decrease) AirInterceptRange of a unit using promotions.
- Gold and production now 4x and 2x of the value stated in the PolicyGEorGM column.
- Yields scale with era according to the current formula, as well as game speed.
- Great person points granted from one policy unlock will always the same. Previously, if a great person is born while the game is cycling through cities, the points you get for subsequent cities will change.
- Since the column isn't used anywhere, I hope it's fine if I just edit it directly like this.
- Commented out a few lines that have to do with stackwalker just to get the original DLL to compile. Not sure what …
=> AirInterceptRangeChange and PolicyGEorGM

CPPSetupData.iss
Turn on logging automatically via the installer to ease of troubleshooting issues.
=> Automatically turn on logging via the installer

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
- Added table Trait_DomainFreeExperienceModifier.
- Increases the free experience you get (eg from buildings or policies) for a certain domain.
- Fixed missing CoreTableAdditions.xml.
=> Trait for modifying starting free experience

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
- Does AoE damage to adjacent units equal to the integer defined in AoEDamageOnMove when a unit moves (including melee units after killing another unit).
- Changed function CvUnit::DoAoEDamage so that the string tag to be displayed is an argument. Changed code relating to AoEWhileFortified to account for this.
I do not see any functions in the whole DLL which takes char 256 as an argument. Is there a particular reason for this?
=> Added column AoEDamageOnMove to UnitPromotions

Community Balance Patch/Balance Changes/Text/en_US/UnitText.xml, Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h, EUI Compatibility Files/EUI Compatibility Files/LUA/EnemyUnitPanel.lua, NoEUI Compatibility Files/Mod Template1/LUA/EnemyUnitPanel.lua
- Added table UnitPromotions_CombatModPerAdjacentUnitCombat. The unit with this promotion gets combat bonus based on the number of friendly units nearby of the specified unit combat types.
- Also found a possible bug in line 349 and 350 of CvUnit.cpp.
Haven't thought about this before, but is there a practical limit to the amount of new code / tables you can add to the DLL?
=> Prussian Discipline

43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/43 Civs CP/No-EUI/CivilopediaScreen.lua, Community Balance Patch/LUA/CivilopediaScreen.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua, NoEUI Compatibility Files/Mod Template1/LUA/CivilopediaScreen.lua
GameInfo.Eras is not updated after mods are loaded. New Era (e.g. EE) breaks Civilopedia.
=> Civilopedia Era fix

43 Civs CP/43 Civs CP/EUI/EnemyUnitPanel.lua, 43 Civs CP/43 Civs CP/No-EUI/EnemyUnitPanel.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/EnemyUnitPanel.lua, NoEUI Compatibility Files/Mod Template1/LUA/EnemyUnitPanel.lua
- EnemyUnitPanel.lua should now correctly display bonuses from UnitPromotions_CombatModPerAdjacentUnitCombat for all cases.
I double-checked that the encoding is UTF-8 this time, hopefully no problems here.
=> Per adjacent ui fixes

Community Balance Patch/Balance Changes/Text/en_US/BuildingText.sql
There was a space missing after the comma in Circus Maximus description
=> Circus Maximus

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvGame.cpp
After loading an MP game the first turns of human players can often be skipped, meaning the AI gets two turns in a row. I traced the problem down to being a result of the players erroneously being flagged as
having already submitted their ready message for the turn. The fix isn't really a fix as I believe the problem is in the host. Instead I just check for the problem upon the first activation of the local player and
send the unready message if need be. 
In short, HasReceivedTurnComplete was sometimes already returning true after a load so I call sendTurnUnready when it does so their turn doesn't end immediately.
I have played a few games (2 human/6 AI) with the change and have not noticed any negative effects but maybe you can. 
I can probably dig up some save games which exhibit the …
=> Fix for skipped turn on load in MP issue

CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp
Looks like a bool was named incorrectly, leading to some inverted logic.
The bug would cause valid deals being withdrawal by the AI and invalid
deals no withdrawn.
The bug had been addressed by the time I got around to submitting the fix but I am not sure if the fix that was checked in is the best solution since I believe it would result in bad deals being presented to the player.
I have an upcoming pull request that does actually remove this condition but also implements logic to try to adjust the deal so that it is acceptable before presenting.
=> Fixed issue with Active Diplomacy deal request withdrawal logic

CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp
A couple of errors in CvDiplomacyRequests::CheckRemainingNotifications()
which could result CTDs, the wrong details used in deal withdrawal
notifications, or deals could be skipped over.
This is due to the
erasing during processing which also assigns back to the iterator before
it has finished using it. The iterator would then be pointing to the
next element, which could even be end(). Also the iterator essentially
being incremented twice but would be processed on the next call to the
function and not be a real problem in reality.
=> Fixed iteration over Active Diplomacy deal request notifications

CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp
Now using getName() since nicknames are not populated for AI players, it
seems. getName() is used with much success all over the codebase.
There are still many instances of getNickName being used elsewhere. They obviously must work sometimes but it is definitely not always the case. I am of the opinion that getName is the better choice since it looks to be coded to handle all situations. Your thoughts?
=> Fixed blank names in AD deal withdrawn notes

CvGameCoreDLL_Expansion2/CvDllGameDeals.cpp
Prevents getting a counter offer notification instead of a deal proposed
notification to self when making a human-human deal with Active
Diplomacy active.
=> Fix erroneous counter-offer notifications with Active Diplomacy

CvGameCoreDLL_Expansion2/CvNotifications.cpp
Deal proposed notifications for human to human deals were getting
swallowed up by Active Diplomacy code when active, meaning the recipient
did not know they had deals waiting.
Not sure why the original code was the way it was and
maybe I don't understand the problem properly.
=> Fix lack of human-human deal notifications with Active Diplomacy

CvGameCoreDLL_Expansion2/CvDllGameDeals.cpp
At least after my other changes (possibly before also) there were errors in the failed AI diplomacy logs about human to human deals. Just skipping the Active Diplomacy code again for human-human deals seems to fix the issue and not cause any more either.
Didn't investigate much do due the history of similar problems.
=> bypass Acitve Diplomacy FinalizeDeal code for human-human deals

CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp
Add in chance to equalize Active Diplomacy deal before opening
Cached peace value wrecking havoc with AD deals (well vice versa, I
guess). Now AI will check the deal just before notification is activated
by human and attempt to equalize it. Unacceptable deals will no longer
be removed just after other deals have finished activation, as a
supporting change.
Here is a save file from a VP 2-27 game that can demonstrate the problem and fix:
[Catherine_0245 AD-1950.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1913045/Catherine_0245.AD-1950.zip)
(Forgive our poor VP skills. We are new and bad)
Play as Egypt. Arabia will offer peace but will remove the offer if you accept Denmark's offer. This is because of change in your happiness (or something, I can't remember) from that deal. …
=> Active Diplomacy JIT deal modification

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
I discovered this by reading the code and I only speculate that this would cause desyncs. This is because it has code that modifies state that is only performed on the active player.
Changed so that the only the UI related code is the only code exclusive to the active player.
Unfortunately, I have not come across this in testing.
=> fix desync from sharing opinion

CvGameCoreDLL_Expansion2/CvPlayerManager.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp
This data depends on the warring state but is only updating in the event of war being declared. It seems to me it should be updated on peace too, keeping in mind that the parties could still be at war with other players.
Also renamed arg since it is being called for peace now too.
Code was simply copied from declareWar but am not fussed at the moment. In an upcoming pull request I remove some of this code since I don't think it is particularly as effective as it could be. I plan on cleaning up once proven effective and agreed as the right course of action.
=> refreshing some cached data on make peace

CvGameCoreDLL_Expansion2/CvPlayerManager.cpp
Despite what the code comments say, I believe some trade routes calcs depend on the war state and they should be updated when it changes.
This done in a very heavy handed fashion because I don't trust the cache
to actually be updated even though it is invalid when accessed.
The location in which I am doing this is far from ideal as the cache will be refreshed multiple times unnecessarily. Ideally I would just invalidate the cache but, as stated above, I think the caching is somewhat deficient.
I would like to address the issue by making the cache access more fool-proof but that will take some more time and testing.
=> refresh TR cache on war state change

CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.cpp, CvGameCoreDLL_Expansion2/CvPlayerManager.cpp, CvGameCoreDLL_Expansion2/CvTacticalAnalysisMap.cpp, CvGameCoreDLL_Expansion2/CvTacticalAnalysisMap.h, CvGameCoreDLL_Expansion2/CvTeam.cpp
Tactical data is desyncing. I believe it is largely to do with the caching mechanism on the TacticalMap.
The TacticalMap is only updated at most once per turn due to existing caching logic. I suspect that the data is desyncing due to the cache being updated at different points on some clients. Unfortunately I haven't figured out the conditions in which the update points are different. Instead I have tried to minimise the potential to desync by forcing updates at specific points. I have also added the ability to invalidate the cache so that the cache is still rebuilt at a later point in the turn (as seems to be desired, otherwise there would not be a need to be lazy about the updates).
This change is very heavy handed but does appear to help prevent desyncs. It can be cleaned up and …
=> TacticalMap updating and desyncs

CvGameCoreDLL_Expansion2/CvUnitMission.cpp
Largely fixes a variety of trade route related desyncs, such as ones caused by different paths etc. This small change will greatly improve MP experience. I reckon that this bug may have played a big role in the increased complaints about MP after BNW was released.
TR Cache was being updated only on the owner's client. Need to update on all or else route details could be different leading to desyncs. This is now done by invalidating the cache when the establish trade route unit mission is received.
I suspect there is still the potential for desyncs if the user opens the TR popup but something changes before they issue the command. Even just opening the popup could cause problems. I think a net message is in order for a real fix and I will look into it.
=> Make Trade Route desync

CvGameCoreDLL_Expansion2/CvDealClasses.cpp
DiplomacyAI_TradeAgreements_Log.csv wrong in one instance.
=> fix typo in trade log name

CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h
There was a static bool called ProcessPlayerAutoMoves in updateMoves but I made it a member. This due to the static var not being re-inited and maybe causing issues when loading after an exit-to-menu and starting/loading a new game (maybe with different turn types). The member is not serialized, should be OK.
If the static var started off true I think it may have been possible that automoves might processed before they should have been (probably only in  Simultaneous MP with no AI). I don't fully understand the turn process but the code seems to think it important to not start before everyone is ready.
While writing notes for this pull request and trying to document what issues this actually fixes, I noticed what seems like a bigger problem. If in Simultaneous MP with no AI (only), the …
=> ProcessPlayerAutoMoves reinit issue

CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyRequests.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp
ACTIVE_DIPLOMACY specifc code was removed from writing out proposed deals.Comments stated that it was not writing out requests until issues were resolved. I am not sure what the issues were but I may have addressed them. It seems to work OK, albeit still a little odd because I need to clean them out at the start of the turn.
Diplo requests are now being written out also.
I don't think this change has much effect unless you are writing new save games in the middle of the turn, such as "double saving" or using the "mp post autosave" feature I will be submitting shortly. I guess some associated changes (sending the requests to non-active players) might prevent some weird desyncs but probably not.
I don't think I have tested this enough yet for a proper release but I have not had any issues …
=> Save Diplo Reqs and Proposed Deals

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvDllNetMessageExt.cpp, CvGameCoreDLL_Expansion2/CvDllNetMessageExt.h, CvGameCoreDLL_Expansion2/CvDllNetMessageHandler.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/VoxPopuli.vcxproj
Added code to send Event related messages to remote players. However, this is done via the foul means of hijacking the DiplomacyFromUI message and giving it a dual purpose. Event messages are have a flag encoded into one of the arguments and this is detected and handled appropriately on the clients. I understand this is unappealing but I believe it to be safe and the nastiness is tucked away.
Seems to work fine but maybe some events are problematic as I wouldn't have encountered all variations of mechanisms in limited testing (only 2 players!).
Added code is nothing fancy and can be improved if we want to send more
of messages in this manner, such as making the Trade Route cache invalidation when opening the TR popup propagate to other clients.
=> Enabled Events in MP

CvGameCoreDLLUtil/include/CvEnums.h, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h, CvGameCoreDLL_Expansion2/CvSaveController.cpp, CvGameCoreDLL_Expansion2/CvSaveController.h, CvGameCoreDLL_Expansion2/VoxPopuli.vcxproj
Due to the barrier on the finishing of AI processing, it looks like it *might* be safe to slot in a second autosave point after AI has finished but before humans. This means that when loading, players do not need to wait while they watch the AI have their turns and (from memory) has the added bonus of not allowing the AI to have two turns.
Unfortunately, saving at this point can result in a slightly unpleasant stuttering of the game. Nothing too bad but some may not like it and not want it enabled. Also because of the was MP saves work (copying the most recent autosave) the post AI save will be used for manually saved games also.
In order to give people better choice as to when to have the post AI save enabled I have also added a couple of GameEvents which allow the various autosaves to …
=> Added second autosave point and save events

Community Patch/Community Patch.civ5proj, Community Patch/Core Files/CoreLua/MPList.lua
The fix is a bare minimum. Each observer will have their own "Observers" label, which seems odd but I guess that is the way it is - better than the whole list not being visible at all.
Is the file in the correct location though?
To repo, just create a MP game with observers. The observer slot may need to be empty. I had 1 human and 2 AI. The player list in the UI will not be present and there will be a error in the lua log.
=> fix runtime error in mplist.lua with observer slots

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvPlot.cpp
Issue when revealing plots during plot visibility count update.
Return value from CvPlot::setRevealed is more nuanced than simply
returning whether the plot is being revealed to the team.
Now using a simple check for when deciding on whether the explore plots list needs amending.
This will be responsible for a large number of desyncs for people who autoexplore. When autoexploring the unit could choose a different plot to explore since it is selecting from a different set of potential plots as the active player has reveal plots that the other machines do not.
This bug causes all sorts of problems, particularly desyncs in MP.
While the position is possibly synced by host, the visibility of the
plots is not. This means things like barb camps get spawned in different
locations on different …
=> fix bug where plot reveal was dependant on active player

CvGameCoreDLL_Expansion2/CvDllNetInitInfo.h, CvGameCoreDLL_Expansion2/CvPreGame.cpp, CvGameCoreDLL_Expansion2/CvPreGame.h
Fix issue with 32-bit shift for 32-bit value in code to keep civs unmet in pregame
Also, using more sensible types now.
=> Fix issue 32/64 bit bit shifting when keep civs unmet pregame

43 Civs CP/43 Civs CP/EUI/NotificationPanel.lua, CvGameCoreDLL_Expansion2/CvNotifications.cpp, EUI Compatibility Files/EUI Compatibility Files/LUA/NotificationPanel.lua
Deal notifications all now have the proper civ background, instead of the orange colour.
The code for AI senders was actually present in other versions of the Lua.
The code for the human senders is a bit a hack but safe enough.
=> Civ background on all MP deal notifications

CvGameCoreDLL_Expansion2/CvDllNetMessageExt.cpp, CvGameCoreDLL_Expansion2/CvDllNetMessageExt.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h
Addresses double turn issue for pitboss games when players are not
initially present when the host starts.
Implemented a new message that intends to do some of the same job that sendTurnComplete is supposed to do and will prevent human turns on remote machines ending before they should.
=> Added extra condition for the ending of the first MP turn to prevent double AI turn bug with Pitboss

CvGameCoreDLL_Expansion2/CvDllNetMessageExt.cpp, CvGameCoreDLL_Expansion2/CvDllNetMessageExt.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h
Reverts LoneGazebo/Community-Patch-DLL#4330
I am getting some strange behavior where the first turn does not progress under certain conditions. I believe it is due to this change as I have not encountered it before now.
Reverting until I can figure it out.
=> Revert "Added extra condition for the ending of the first MP turn to prevent double AI turn bug with Pitboss"

CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
- Original owner property now transfers when unit is converted (eg upgraded, etc).
- Promotion instant yields no longer trigger when unit is upgraded if promotion is retained on upgrade.
=> Meiji 17/02/2019

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Thought I'd make a contribution to my most frequently-consulted file.
I'm no expert in C++ so these changes were made by examining the surrounding code and extrapolating from it - please verify that these are actually written correctly! :)
Fixes the following issues:
- Minor text fixes for comments
- Fixed typo in function name for GetNoSettleRequestScore (was GetNoSetterRequestScore)
- Commented out GetGaveAssistanceToScore and GetPaidTributeToScore in GetMajorCivOpinionWeight function, since those functions always return 0 and there is no code for their functioning - so no need to perform that check for every major civ every turn
- Master war/hostile weight towards vassals: now checks for number of capital cities being greater than 0, not if the original capital was conquered (for …
=> Minor Bugfixes and Optimizations

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
- After looking at the GetNumCapitalCities function I realized it does not factor in a player's original capital, only captured capitals of other players, so this fixes the vassal weight check to not zero out the weight if they have either their own capital OR anyone else's capital (again, for Domination Victory reasons).
- Everything else is comment text fixes with no code changes. Fixed typos, inaccuracies, some clarifications and small additions, and added an explanation comment before a lot of functions that didn't have them, for easier understanding (not opinion modifiers as they're pretty self explanatory).
=> Capital check + comment fixes

Community Balance Patch/Modular Elements/Corporations/Text/en_US/CorpText.xml, CvGameCoreDLL_Expansion2/CvCorporationClasses.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
- Added support in corporation office benefit string for multiple types of bonuses at once.
- Now transfer memory of promotions ever obtained in CvUnit::init() rather than CvUnit::convert(), as promotions can get granted before the convert function is called.
- Fixed call to doInstantYield for the promotion instant yield not using the pCity variable.
- Removed logic in promotion instant yield to use capital as the origin city, if origin cannot be found (getOriginCity() already does this).
=> Meiji 12/05/19

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvAIOperation.h, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
- Fixed an issue where breaking a City-State attack promise with one civ gave you immunity to the opinion penalty for ignoring other civs' request to stop attacking a protected CS. As the global opinion penalty for breaking a CS attack promise is 0, it was illogical for it to be cancelling out the ignore penalty - although I left the original code commented out with the syntax fixed.
- Fixed the sloppy syntax for ignored/broken promise opinion modifiers
- A few text fixes
GetMajorCivOpinionWeight:
- Rearranged the order of the modifiers to make it more neat and categorized; changed comment text slightly (does not change the code).
- Commented out GetBrokenAttackCityStatePromiseWithAnybodyScore because it always returns 0.
DoEstimateOtherPlayerOpinions function:
- Now factors in DoF, DP, …
=> More Minor Diplomacy Tweaks

Community Balance Patch/Balance Changes/Text/en_US/BuildingText.sql, Community Balance Patch/Balance Changes/Text/en_US/UIText.sql, Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Makes the following changes:
**NOTE:** I'm not 100% confident on the syntax for the changes to the Approach guess function and would appreciate if it was looked over, although I tried my best and revised it several times.
Text
- Fixes the typos in the Workshop, Terracotta Army and <50% approval rating descriptions.
- Comment fixes/optimizations.
LuaPlayer
- Added text keys for the improved embassy opinion modifier, see below.
- Added a text key in GetOpinionTable for AI teammates of humans. ("We are on the same team.")
Diplomacy AI
- Adds original capital capturing, ideologies, social policies, and the diplo bonus for a master towards a vassal to the AI's DoEstimateOtherPlayerOpinions function. Working on adding more to this soon.
- Fixes a bug in GetPolicyScore that was preventing …
=> Smarter AI approach estimates and a few more diplo changes

CvGameCoreDLL_Expansion2/CvDealAI.cpp
All instances of bHideTrueFeelings being set to true when obtaining the AI's approach for deal valuation were removed recently.
As such, this adds a case for WAR and DECEPTIVE in each instance where they're missing.
In these added cases, DECEPTIVE is always set to the default value for the switch statement; WAR is set to INT_MAX where HOSTILE and GUARDED also are, and to the default value otherwise.
=> DealAI bHideTrueFeelings Approach Valuation Fix

CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
- Added checks to prevent duplicate entries in std::vector containers.
Not sure how necessary this is, but shouldn't hurt to have, since they should not be called that often.
Also, I cannot compile the DLL with all the latest commits, seems to be a bit of a bad merge going on right now.
So I can't really test it now, but its simple enough, so hopefully ok.
=> Trait_NoBuilds 13/07/19

Community Balance Patch/Balance Changes/Text/en_US/CivText.sql, Community Patch/Core Files/Text/CoreText_en_US.sql, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, NoEUI Compatibility Files/Mod Template1/LUA/EnemyUnitPanel.lua
Clarify reckless expander text key
Fix issue #5421 
Typo fixes
Fix Ethiopia UA description
Removed reckless expander penalty for teammates
Reckless expander average no longer factors in Barbarians, players with no cities (a possible occurrence with Complete Kills enabled), and unmet players
In the unlikely event that a player has the HOSTILE approach at the time of ending a DoF for any reason, it won't be set to GUARDED upon ending it, and same for the war face.
=> Tweak Reckless Expander Penalty

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp
Fix exploit where players who promised not to attack the AI would null their war/hostile weight
Fix issue where AIs that made a military promise wouldn't reduce their war/hostile weight
Fix issue where AIs that made a military promise wouldn't factor this in when declaring war or starting a coop war
Cleaned up syntax in DoPlayerDeclaredWarOnSomeone, was messy with unnecessary variables
Moved city liberation bonus removal to DoPlayerDeclaredWarOnSomeone
AI will now recognize when a player has broken a coop war promise by declaring war on them, and penalize them accordingly
AI will end all coop war agreements when a DoF is ended by either party. The party who ended the DoF will receive a penalty for breaking the promise. (Modified the text key to make this change clear to the human)
Reset …
=> More Promise Fixes & Improvements to DoPlayerDeclaredWarOnSomeone

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Ref. #5552
Not sure what is causing this to happen (perhaps a mod conflict, or some change to the city capture code), since I don't remember altering this at all
However, this should fix it, regardless of what the cause is. I would look more into it, but I'm going on vacation without computer access for a while as of tomorrow, so this'll have to do for now unless someone else wants to take a look at it :)
=> Temporary bugfix for warmongering penalties on first contact

Community Balance Patch/Balance Changes/Difficulty/DifficultyMod.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Reorganizes DifficultyMod.xml to make it more accessible and customizable to players or modders looking to change the handicap settings.
Categorizes the various bonuses/penalties for easier modification.
Adds certain entries (e.g. FreeCulturePerTurn) that were omitted but functional, although the default values are used, so this will not change gameplay. I have tested the changes and they are functional.
Adds a link to a guide I created on this subject: https://civ-5-cbp.fandom.com/wiki/Customizing_Difficulty_Levels
**(NO BALANCE CHANGES MADE TO DIFFICULTY VALUES)**
According to what you said in April 2018 here (question 35 reply), reorganizing this file is fine as long as no columns are missing :)...and yes, the reason I asked that question was because I intended on making this pull …
=> Reorganize DifficultyMod.xml & Small Fixes

Community Patch/Core Files/Text/CoreText_en_US.sql, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h
Separates yield evaluations for Gold, Science and Culture in the diplo AI's trade check as discussed in #5717. Maybe you want to adjust the scaling factor to reflect the separation?
Ready for you to add in the yields from deals, G.
=> Improve Diplo AI Trade Check

Community Balance Patch/Balance Changes/Difficulty/DifficultyMod.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Clean up various diplo-related code
Changed the placement of code sections which zero out approach weights to be after the opinion calculation
Changed IsWantsToConquer function:
- AIs locked into a coop war/trade war against the target who are also fiercely competitive with the target will now ignore target value (added this because of a similar check in GetCoopWarScore)
- AIs who are locked into a coop war/trade war against the target but are not fiercely competitive are treated as bold AIs (since they're backed up by another player, after all)
- AIs will always want to conquer major civs they're at permanent war with (set by game options).
- These changes make the AI more likely to carry on with wars that they initiate, since you can only get locked into a coop/trade war by your own …
=> Diplo Fixes & Improvements

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
Also clears it when war begins.
If you can steal a city without a permanent diplo penalty, you should be able to do the same with land. :)
=> Remove penalty for stealing territory during war

Community Balance Patch/Balance Changes/Text/en_US/UnitText.xml
Why this fix https://github.com/LoneGazebo/Community-Patch-DLL/pull/5891/commits/5772b8539b96318ab41da62cf513169923c1ab34 never merges into any new VP release? (Fixes Diplo Units Typo)
=> Small Typo Fixes

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/CvUnitMovement.cpp
Another request from pineappledan. "The ability to give units free movement points on embarkation, or to not lose movement points if they embark. Whichever is easier."
In this case I made no movement point loss on embarking. I put a counter in like the double movements. Hopefully that's what prevents an infinite movement loop.
=> Promotion: Free Embark

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
Another request from pineappledan. "A promotion table that lets you define a yield that the player gets every turn if that unit is garrisoned in a city, Fort, or citadel." Considering there's already a promotion table for garrisons, I simply added one for fortifications.
I'm not sure if I did the correct logic for getting the combat unit on the plot. Specifically line 9815 of "CvPlot.cpp".
=> Promotion: Fortification Yield

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.h, CvGameCoreDLL_Expansion2/CvPlot.cpp
I have added the table entry.
I'm sorry if I still messed it up. New territory for me.
Once again, the goal was for "a build requirement for a unique improvement that allows it to be built next to any water: Lakes, rivers, coast. AnyWater exists for buildings, but not for Improvements"
=> Improvement: Body of Water Makes Valid

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
Another request from pineappledan. "A trait that disables a player’s ability to stop razing once it has started"
It's intended for his Timurid mod. Only thing that is a concern is the UI not having the "stop razing" button greyed out.
=> Trait: Unable To Cancel Razing

CvGameCoreDLL_Expansion2/CvDealClasses.cpp
Can no longer trade resources which either player have not unlocked.
=> Bugfixes 15/12/19

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.h, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/CvUnitMovement.cpp
UnableToCancelRazing and AnyBodyOfWaterMakesValid are working. FortificationYield has been fixed with this.
I have removed FreeEmbark and have overhauled it. Now split into EmbarkFlatCost and DisembarkFlatCost. A unit with the EmbarkFlatCost promotions embarks for one movement point. A unit with DisembarkFlatCost disembarks for one movement point.
=> Fix API Additions

43 Civs CP/43 Civs CP/CP Only/ReligionOverview.lua, 43 Civs CP/43 Civs CP/EUI/ReligionOverview.lua, 43 Civs CP/43 Civs CP/No-EUI/ReligionOverview.lua, Community Balance Patch/LUA/ReligionOverview.lua, Community Patch/LUA/ReligionOverview.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/ReligionOverview.lua, NoEUI Compatibility Files/Mod Template1/LUA/ReligionOverview.lua
This fixes issue #6048.
I have tested these changes in my current game successfully; I also checked the vanilla files and this actually seems to be a vanilla bug.
Since this is my first pull request, please let me know if I did everything correctly; I hope I didn't miss any file or other change that I was supposed to do. Implementing this by editing the ReligionOverview.lua file in my MODS folder (of the last overriding mod, which in my case is the Religion Spread mod), clearing the cache and running the game shows that the issue is successfully fixed.
=> Fix numeric sorting in Religion Overview

43 Civs CP/43 Civs CP/EUI/NotificationPanel.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/NotificationPanel.lua
Fixes #5801 by adding the war info that is otherwise only shown in the Leaderscreen to the war icon tool tip, which otherwise contains either no or almost no information and often shows an empty tool tip. Also fixes the first line of the tool tip always being empty and removes the "at war with" line, which wasn't being loaded anyway. Tested and verified locally. See how it looks:
=> Fix #5801: add war info to war icon tool tip

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
Fixes #6097
Note: GitHub said that it changes the formatting of the file to UTF-8 when making commits here through the website (that's why line 2 was automatically changed...it's the icon code), so if that's a problem it would be better to decline this pull and apply this fix yourself, locally (see details in the referenced issue or look at the two changes in line 15477 and 15479 in this pull request).
=> Tribute reluctance decay fix number 2

43 Civs CP/43 Civs CP/EUI/CityBannerManager.lua, 43 Civs CP/43 Civs CP/EUI/CityBannerManager.xml, EUI Compatibility Files/EUI Compatibility Files/LUA/CityBannerManager.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CityBannerManager.xml
This adds the functionality presented and discussed in [this forum thread](https://forums.civfanatics.com/threads/community-poll-adding-a-more-easily-visible-tribute-breakdown-to-city-banners.653678/) to the EUI versions; the poll currently shows overwhelming support (21 in favor, 1 against) for it.
The rationale is laid out in the OP of the forum thread. Tested and verified; also makes the war outline for foreign Cities a bit more symmetrical and adjusts a bit the (invisible) outline of the City Banner button.
=> Adding Tributing UI element to Minor City Banners

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Fixes the issue mentioned [here](https://github.com/LoneGazebo/Community-Patch-DLL/issues/6118#issuecomment-574640843): war damage level should be updated before assessing peace willingness, as is correctly done in the DoTurn method of the diplo AI.
=> making sure peace willingness evaluation has up-to-date info

43 Civs CP/43 Civs CP/EUI/NotificationPanel.lua, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h, EUI Compatibility Files/EUI Compatibility Files/LUA/NotificationPanel.lua
Fixes #6118 
Also fixes a bunch of other potential issues; as described in the relevant issue this adds two new LUA hooks to update war related data in the diplo AI.
I also made sure to make the blanks uniform, which is why some leading spaces are converted to tabs for entries I otherwise didn't modify, as is the case for most of the code, so it's displayed consistently across editors.
=> Fix war icon tool tip issues

Community Balance Patch/Balance Changes/Units/PromotionChanges.xml
Adds promotion OrderPriority attributes to those promotions that are missing them while their counterparts have them (e.g. Coastal Raider and Boarding Party promos didn't have this, yet Targeting and Bombardment did) and modifies it for some that had nonsensical OrderPriority values like Siege Inaccuracy and other similar promos had OrderPriority 1, which doesn't really make sense as those don't need to be in the first, best spot since they can't be chosen and don't vary unit by unit.
=> fix missing or nonsensical promotion OrderPriorities

Community Balance Patch/Balance Changes/Text/en_US/CivText.sql, Community Balance Patch/Balance Changes/Text/en_US/UnitText.sql
Literally all air unit strategy entries in the civilopedia were partially incorrect. This fixes that and makes them more robust to future changes.
=> fixes for air unit strategy entries

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvUnit.cpp
Now factors in military skill through a rating system, equal to total war value gained/lost (not counting decay, razing or Barbarians).
Plus a few small tweaks.
Not savegame compatible (adds new memory value).
=> Improvements to diplo AI military strength estimation

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvTechClasses.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
- Fixed potential crash due to division by zero in CvPlayerTechs::AddFlavorAsStrategies.
- Fixed missing lua method unit:IsWithinDistanceOfCity.
- Fixed crash when creating free city, when the new free city owner is a maritime city state.
- Fixed potential crash due to null plot in CvMinorCivQuest::IsExpired.
=> Bugfixes 26/02/20

CvGameCoreDLL_Expansion2/CvCultureClasses.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp
Some of the events were triggering the difficulty bonus and incrementing ChangeNumHistoricEvents even when the civ didn't get tourism bonuses; some of them weren't. Now they all at least trigger the difficulty bonus, which is consistent for game difficulty.
Fixed land and sea TR historic events not triggering the AI's difficulty bonus.
Slightly more detailed logging for difficulty bonus (DIG/TRADE).
=> Difficulty bonuses always trigger (even without tourism bonuses)

CvGameCoreDLL_Expansion2/CvPlayer.cpp
Because otherwise, it can result in a feedback loop - and with all the other bonuses the AI gets when they have a Golden Age, I think it's superfluous. They get GAP from numerous other sources, including the difficulty bonuses for new eras, wars, Wonders and Great People.
=> Remove GAP from Golden Age difficulty bonus

CvGameCoreDLL_Expansion2/CvUnit.cpp
My bad on this - I did not notice that non-combat XP was already given a gamespeed scaler in CvUnit::changeExperienceTimes100. The change in this version can therefore be reverted.
=> Fix double XP scaler

43 Civs CP/43 Civs CP/EUI/EnemyUnitPanel.lua, 43 Civs CP/43 Civs CP/No-EUI/EnemyUnitPanel.lua, Community Balance Patch/LUA/EnemyUnitPanel.lua, Community Patch/LUA/EnemyUnitPanel.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/EnemyUnitPanel.lua, NoEUI Compatibility Files/Mod Template1/LUA/EnemyUnitPanel.lua
**Before (MISSING unit health modifier for attacking ranged units)**
**After (WITH unit health modifier, damaged ranged unit does lower damage than the fully healed because of unit health modifier, which is now shown**)
=> Some Typo Fixes

CvGameCoreDLL_Expansion2/CvTechClasses.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
Tweaks to promotion logic including for barrage change and added values for amphibious.
Vanguard (known as COASTAL_TERROR in xml) says it has 100 damage vs cities in game, but xml has value of 125. Didn't change this as I don't know which is correct.
Base Tech cost formula updated to be multiplicative rather than additive.
There are some other issues with tech cost and particularly overflow which I will mention in a separate issue.
=> Small updates

Community Balance Patch/Balance Changes/Text/en_US/BuildingText.sql, Community Balance Patch/Balance Changes/Text/en_US/BuildingText.xml, Community Balance Patch/Balance Changes/Text/en_US/UnitText.xml
Removed redundant info for Well and Watermill cause you can't choose between them anyway.
=> Small fixes

Community Patch/Mapscripts/Communitu_79a.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/AssignStartingPlots.lua
AssignStartingPlots changes:
- Less bonus resources overall
- Even less stone
- Bananas are in tropical areas only
- Less iron and horses, and each major deposit is 2-4 instead of 3-5
- Tundra/desert major horses are 2-3
- Bison can spawn 3 tiles around start positions
Communitu_79a changes:
- Map options shuffled to put resource options at the bottom
- Land Shapes option effect much more apparent (Extremely Stringy is REALLY stringy)
- Strategic Balance and Legendary Start options merged into one (Starting Resources)
- Resource amount based on AssignStartingPlots but slightly lowered to compensate more land
=> AssignStartingPlots and Communitu_79a update

CvGameCoreDLL_Expansion2/CvCity.cpp
- Disable thorough building type checks for CvCity::UpdateHappinessFromBuildingClasses(). It was taking far too much CPU.
=> rsi 10/01/21

Community Balance Patch/Balance Changes/Beliefs/Pantheons.sql, Community Balance Patch/Balance Changes/Leaders/GodsKings/GKLeaderChanges.sql, Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp, CvGameCoreDLL_Expansion2/CvBeliefClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
- Refactored CvCity::UpdateHappinessFromBuildingClasses() for MOD_BUILDINGS_THOROUGH_PREREQUISITES. Should not freeze the game when conquering cities now.
- Added IsEraScaling column to Belief_YieldFromTechUnlock.
- Added IsEraScaling column to Belief_YieldPerBorderGrowth.
- Celt's Epona pantheon now scales with era as described in tooltip.
- Fixed Lua method unit:GetBlastTourism(). Now correctly shows the tourism the unit would grant if it was to perform a concert tour with the player whose plot it is on.
- Tooltip when performing concert tours now correctly show the actual amount of tourism after modifiers gained with the player.
Save game compatible.
=> RSI 13/01/21

CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
- Fixed Trait_YieldChangesPerImprovementBuilt triggering more than once when there are multiple yield types define for one improvement type.
=> RSI 14/01/21

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvCity.cpp
- Added Lua hook CityExtendsWLTKD. Counterpart to CityBeginsWLTKD, which accounts for cases when the WLTKD turn count is increased, but the city is already in WLTKD.
=> Misc 07/02/21 n2

CvGameCoreDLL_Expansion2/CvCity.cpp
- Extra border Growth now applies to border expansion even if culture per turn in city is 0.
- burghers (fealty) policy now also doubles the extra border growth.
- Fixed a bug where if the next best border growth tile is outside the BuyPlotDistance (3), then cost for purchasing any new tile will increase a lot.
- Left a comment about an issue where Burghers (fealty) policy doubles border growth speed during Golden ages also, though tooltip says only during WLTKD. Will make separate issue about this.
=> Border expansion fixes

Community Patch/Mapscripts/Communitu_79a.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/AssignStartingPlots.lua, NoEUI Compatibility Files/Mod Template1/LUA/AssignStartingPlots.lua
AssignStartingPlots:
- Natural Wonder locations require higher fertility, to properly prevent being put in the middle of nowhere. Side effects might include Krakatoa never being placed, please observe.
- Make sure Natural Wonders can never be 3 tiles around City States (up from 1).
Communitu_79a:
- Tweak shortest path algorithm edge weights so it actually works (no more straight unnatural canals)
- Make sure polar sea connections never dig through land in Terra mode
=> AssignStartingPlots and Communitu_79a changes

CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.h
- Vote trading for Diplo Victory now allowed again. Tbh the whole trading vote system is a bit flawed because it considers choices individually rather than comparing to others. (You wouldn't trade a vote cheaply for something you kinda wanted if you really really wanted something else) This should work for now though.
- Not sure if this was the case before but you can also see how much a civ would want to vote for all the other civs so you can figure out who they are likely to vote for
=> April fixes

CvGameCoreDLL_Expansion2/CvEspionageClasses.cpp
(already checked in CvDiplomacyAI::IsPlayerBadTheftTarget)
=> Remove duplicate checks

CvGameCoreDLL_Expansion2/CvDllDatabaseUtility.cpp
Rationale - In vanilla Civ5 all strategic resources are required to build at least one unit, thus checking if a resource is referenced in Unit_ResourceQuantityRequirements is sufficient to find all strategic resources. However in the CBO, coal is not required to build any units (only buildings).
The result of this is that coal ends up being classified as a bonus resource instead of a strategic resource which prevents it from showing up in the top panel and prevents it from being traded between nations.
Fixes #7266
=> tag resources as strategic if they are referenced in Building_ResourceQuantityRequirements

CvGameCoreDLL_Expansion2/CvUnit.cpp
GAMEEVENT_PlayerCanGiftUnit expects 3 int sized arguments but is being passed a CvPlayerAI object instance as the second argument.
=> fix incorrect passing of CvPlayerAI instance in place of PlayerTypes index

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp, CvGameCoreDLL_Expansion2/CvProcessProductionAI.cpp
- Moved puppet logic to ignore most buildings into CvCityStrategyAI (previous method broke the puppet faith purchase mod).
- NonSpecialistFoodChange column in traits now works in times 100 (eg -100 for -1 food cost).
- Changed citizen food consumption logic to be times 100 for the above (internal change).
=> Misc 14/05/21

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
Unit only gives these effects at the start of the turn (works for GiveExperiencePercent, GiveCombatMod, GiveDefenseMod, GiveInvisibility, GiveOutsideFriendlyLandsModifier, GiveHPHealedIfEnemyKilled, GiveExtraAttacks)
=> Add GiveOnlyOnStartingTurn for promotions

CvGameCoreDLL_Expansion2/CvDealClasses.cpp
- Fixed completing research agreements granting science multiple times per player based on the owned number of cities if the player is not currently researching a technology.
- Science from research agreements now always counts as an instant yield. Previously only counted if the player was not currently researching a technology.
=> Misc 16/05/21

CvGameCoreDLL_Expansion2/CvPlayer.cpp
- Consolidates find best city routine
- Consolidates value modification routine
- Gold rewards now scale with speed by gold percent (previously not scaled at all)
- Golden Age Point rewards now scale with speed by golden age percent (previously scaled by culture percent)
- Apply MOD_BALANCE_CORE check for all MOD_BALANCE_CORE rewards consistently (is this actually desired?)
- Fix TXT_KEY_GOODY_PRODUCTION being displayed twice in the reward message.
- Goody Hut rewards may be given to unproductive cities in the event that no cities are actually productive.
=> goody hut cleanliness and fixes

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/CvSerialize.cpp, CvGameCoreDLL_Expansion2/CvSerialize.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
I've rewritten much of the code related to sync variables after realizing that a lot of performance was being lost due to variable state tracking.
This new code completely decouples the sync system from member declarations which is about as good as it's going to get in terms of singleplayer performance. Sync related code should have zero cost outside of checking if the game is multiplayer when an object is created. The trade-off is that the state of each variable between syncs must be stored somewhere in order to know what has changed between turns and each variable must be checked at the end of a turn.
Because of this multiplayer memory usage will see an increase and the CPU will spend more cycles at the end of a turn gathering sync delta information. The gathering of sync delta …
=> Overhaul sync to favor singleplayer performance

CvGameCoreDLLUtil/include/CvLuaArgTemplates.h, CvGameCoreDLL_Expansion2/Lua/CvLuaArea.h, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.h, CvGameCoreDLL_Expansion2/Lua/CvLuaDeal.h, CvGameCoreDLL_Expansion2/Lua/CvLuaLeague.h, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.h, CvGameCoreDLL_Expansion2/Lua/CvLuaTeam.h, CvGameCoreDLL_Expansion2/Lua/CvLuaTeamTech.h, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
Also declare CvLuaArgs helpers inline instead of static
Fixes #7947
=> Fix CvLuaArgs::toValue usage with CvLuaScopedInstance<> types

CvGameCoreDLLUtil/include/CvLuaArgTemplates.h, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaTeam.cpp
Fix bugs revealed by using static_cast in CvLuaArgs::toValue
It should be noted that some of these errors ~~could have been~~ **are** security risks since we are accepting arbitrary pointers from lua and working on them. Gotta be careful with this.
=> Use static_cast in CvLuaArgs::toValue instead of C-style cast

CvGameCoreDLL_Expansion2/CvGame.cpp
Should fix the player occasionally being unable to found their first city when starting a new game.
No issue exists for this but I've encountered it myself and only decided to look into it because of this post
https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-379#post-16105713
Edit - Forced push to fix branch mixup
=> Dirty closest city map upon new game start

CvGameCoreDLL_Expansion2/CvDllDatabaseUtility.cpp, CvGameCoreDLL_Expansion2/CvGlobals.cpp
CvGlobals::init() currently caches and processes the game database, but this operation appears to be unnecessary and serves to make startup times worse.
Immediately after CvGlobals::init() is invoked the engine retrieves and requests a flush of the database and then performs the cache and process operations a second time.
This reorders some operations in order to try and make the cache that the engine performs the only time the database gets cached and subsequently processed.
I haven't observed anything unusual from these changes and I see no reason why this would cause problems. I've tested this as both a standard mod installation and as a modpack; **however if you do believe this might cause problems let me know and I'll do more testing in any areas requested.**
=> Defer database processing to engine load

CvGameCoreDLL_Expansion2/CvDllDatabaseUtility.cpp
I've found that without this little fix PlotHelpManager from EUI fails to properly populate plot tool-tips when a civilian is selected and a tile is moused over because it relies on the ``CITY_PLOTS_RADIUS`` define. FireTuner will even report these errors constantly.
Was this ever reported? I can't be the only person who has experienced this, right?
Interestingly this only happens with standard mod installs and not with mod-packs created by the Multiplayer Mod-Pack Maker. This appears to be because the tool uses a standalone DLL which does insert these defines. Since the DLL inserts them they end up being dumped into the override XML file it produces. Since they're now in the XML database they are later available when the CBP DLL is loaded.
Edit - I should have mentioned that I play with …
=> Reintroduce base game global defines 

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, Community Patch/Core Files/Core Values/CoreValues.xml, CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.h, CvGameCoreDLL_Expansion2/CvPlot.cpp
Forts, Citadels, and Barbarian Camps have it set to 1,  setting it on another improvement means units won't leave it when they attack like cities.
=> Make modular NoFollowUp for improvements

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
- This is necessary because you can only have one quest of each type at once. So if a city-state was killed with an active quest it was never getting returned to the pool.
=> Quests now cancelled when City-State killed

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.h
I've played a bit with this without encountering anything unusual. It wont make governors intelligently work together to optimize overlapping plots; However, it is good enough to prevent scenarios where rapidly expanding cities begins to starve surrounding puppets of workable plots, which is a particularly common occurrence for Venice.
It should also prevent annoying scenarios where players learns late that a city has been unable to work a high value plot because a neighbor city that cannot work the plot had expanded to it.
Only plots that are out of working range are candidates for use by neighbors and once a neighbor's governor selects a neighboring plot it stays under that city control until the player manually intervenes.
Also included is the removal of some redundant checks.
@ilteroi …
=> Allow governor to select neighbor cities' unreachable plots

CvGameCoreDLL_Expansion2/CvCity.cpp
Civilian purchase cooldowns would affect other unit cooldowns but not the other way around. Surely not intended?
=> fix bug with civilian purchase cooldown

CvGameCoreDLL_Expansion2/CvCityCitizens.cpp
When `CvCityCitizens::OptimizeWorkedPlots` is called with logging enabled and all plots are forced (causing `CvPlot* pWorstWorkedPlot` to be `nullptr`), a crash occurs when it is dereferenced in logging statements such as 
```
pWorstWorkedPlot->getX()
```
=> Fix CvCityCitizens::OptimizeWorkedPlots NPE in logging

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, ISSUE_TEMPLATE
Add recent assist bonus for agreeing to a coop war
No positive recent assist decay during the waiting period for a coop war to begin
=> RSI Fixes & Improvements

CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h, CvGameCoreDLL_Expansion2/CvTeam.cpp
- Use a serialised m_eGameEra to allow m_eGameEra to be accessed without need for calculation from CvGame::getCurrentEra()
- m_eGameEra changed in CvGame::UpdateGameEra() which is called whenever a major civ reaches a new era.
I've used this in my mod for a while and it works well. It reduces calculations for quite a few calls to CvGame::getCurrentEra() and I used CvGame::getCurrentEra() instead of CvPlayer::GetCurrentEra() in some cases to stop the civs which are already further ahead getting even more bonuses than the rest.
=> Game_Era Serialised

CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.h
- bFlippedLogic removed in CvLeagueAI::GetDesiredVoteCommitments
- human desired commitments based on  'yay' if they proposed it or their vote score with bConsiderGlobal 'false'
Fixes #8371 
- **Interest rate change for deal equilization**
@LoneGazebo You may want to increase the EACH_GOLD_PER_TURN_VALUE_PERCENT to 6 to maintain the same feel of interest rate as before.
=> Desired vote commitment fix

CvGameCoreDLL_Expansion2/CvHomelandAI.cpp
- All units now checked to see if they can be upgraded each turn instead of only those recruited by homelandAI
I have used this in my own games and AIs will upgrade their units much faster and I haven't noticed any visible downsides. This could potentially have issues with cancelling units' current orders though I'm not exactly sure how troop movements work.
@ilteroi 
Up to you whether you think this is a good idea or not but could solve #8307
=> Unit Upgrade Priority

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.cpp
(does not break lua, only re-activates a parameter that was there before)
=> fix plot blockade logic

CvGameCoreDLL_Expansion2/CvPlayerAI.cpp
Currently, the AI expends all of its Great Admirals (at the same turn) for luxuries when it has more than one, even when it's happy, as long as it's at peace. Considering that a human player would rarely expend GAs when happy  -except when they really have a lot-, and would instead prefer to keep a sizable reserve of GAs, I suggest these changes as a start.
=> AI fixes for Great Admiral Directives

CvGameCoreDLL_Expansion2/CvCultureClasses.cpp
This is referring to the tooltip in the 'influence by player' screen:
- Fixed some tourism modifiers which were shown in tooltip not actually being applied.
- Fixed a few small errors with the tooltip modifiers shown.
- Tooltip now shows the % modifier which is actually being used, removes unnecessary duplicate code and will make it easier to see in future if tourism modifier is incorrect.
No changes made to the city tooltip for when you hover over your tourism. Imo this tooltip is quite messy and the individual civs' tourism modifiers should be removed here and replaced with something like: "Your tourism to each civilization will be affected by your tourism modifier with them, shown in the tourism screen." for clarity.
=> Tourism fixes

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
Remainders, when chosen, were no longer getting zeroed out, so the religion with the highest remainder would get **all** of the remaining unassigned followers instead of 1. The bug shows itself when there is more than one unassigned follower (common) and/or a religion with low pressure has a high remainder (also common).
Given that a remainder represents a fraction of a follower, no religion should get more than one additional follower from the remainder; instead, given X unassigned followers, the X religions with the highest remainder should each get **one**.
=> Follower Assignment Hotfix

CvGameCoreDLL_Expansion2/CvUnit.cpp
Withdrawal chance reduction is now based on the difference between attacker speed and defender speed instead of solely dependent on attacker speed. This makes withdrawal chance actually do something on naval units.  Fast units (eg mounted) are still good at catching slower units (eg commando).
=> Withdrawal Chance change

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
When Retention is additive with Reduction, retention percentages higher than reduction completely negate Reduction; this can result in Religions that are completely immune to inquisitors without saying so in the help text.
=> Multiplicative Pressure Erosion Resistance

CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitCombat.cpp
Some weird interactions that I noticed while I was checking the Withdrawal Chance changes.  For your consideration:
- Winged Hussars (HeavyCharge) can no longer deal AoEOn**Kill** damage when they force an enemy to retreat after dealing damage (without killing).
- Units with Withdrawal chance no longer bait attackers out of their fortifications (cities, forts, etc.) upon a successful withdrawal.
- Falling back is now animated.
=> Retreat Updates

CvGameCoreDLL_Expansion2/CvInfos.cpp, CvGameCoreDLL_Expansion2/CvInfos.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvTreasury.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
- HumanPerEraMod and AIPolicyCatchUpMod added
- Comments about unit upgrade cost and AI supply limit
AI Supply Limit: seems to be reduced per era as it's modifier by AIPerEraModifier which is negative
AI upgrade cost: I think it's modified by AIPerEraModifier twice since the base cost of unit upgrades are already modified by AIPerEraModifier. Might be for the best since unit upgrades get expensive late and they really should do them.
=> Some changes for my new difficulty mod + commented questions

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvAIOperation.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvSerialize.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
This should give distance gifts near parity with normal unit gifts as well as prevent them from receiving AI bonus exp.
Also attempts to fix units not receiving refund exp for promotions lost during upgrade.
=> Normalize unit gifting behavior

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvCity.cpp
Allows oversupply production until the maximum penalty is hit (14 units)
=> Allow oversupply production for hoomans

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
Fix for the Belief spam in the ReligionOverview panel.
This function is primarily used with the PermanentPantheons mod, which should be returning true with player's created pantheon, not the pantheon of their current religion.
#8631
=> HasCreatedPantheon

CvGameCoreDLL_Expansion2/CvCity.cpp
yields from foreign followers no longer added up per city; sum all of the followers first, then divide by the divisor.
=> Syncretism modification

Community Balance Overhaul/Balance Changes/Text/en_US/PromotionText.sql
Updated the text for Amphibious, England's UA promotion.
Moved Blitz into the correct section.
TXT_KEY_PROMOTION_SECOND_ATTACK_HELP didn't exist in the BNW database, so it needs to be inserted.
Everything looks good in game.
=> DB Text Cleaning

CvGameCoreDLL_Expansion2/CustomMods.h
Because why not? Reduces size of the CustomMods struct from 280 bytes to 48 bytes.
=> use 1 bit per custom mod boolean instead of 1 byte

CvGameCoreDLL_Expansion2/CvCity.cpp
The code was copied from getJONSCulture and they left it as divided by 100 but the var is later divided by 100 again..
=> fix Non-Specialist yields being 100x smaller

Community Balance Overhaul/Balance Changes/AI/AIChanges.sql, Community Balance Overhaul/Balance Changes/AI/LeaderFlavors.sql
Tweaked Leader flavors to be more in line with Victory Pursuits. 
- Flavors related to dominant pursuits should be between 8 and 10, secondaries 7 to 9 (depending on how strong the secondary is).
- Mostly incremental changes, except where there was an obvious mismatch (e.g. Ramesses having low archaeology)
-  Balanced out archetype flavors a bit, no default high science for coalition or low air for diplomats etc.
I intend to change archetypes to be based on victory pursuits, not personalities.  I don't feel like going through 1.6k lines again though, so that's for later.
- Spaceship (science victory) grand strategy gave -5 to FLAVOR_RELIGION, which doesn't make sense in VP and got removed.
Note to self: BNW, and also CP, misses 4 entries. In my infinite wisdom I forgot to note them, one …
=> Tweaked Leader and some AI Strategy Flavors

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
so a civ can have an ability to have negative growth during WLTKD.
Expansionist civs will no longer be defined as a civ with any growth boon but only ones with a positive growth boon. (seems to be a specific case for china?)
=> allow negative growth boon

CvGameCoreDLL_Expansion2/VoxPopuli.vcxproj
Adding field to disable the upgrade prompt. Available from 2017 to 2022. Tested on Visual Studio 2019.
https://docs.microsoft.com/en-us/visualstudio/extensibility/visual-cpp-project-extensibility?view=vs-2017#disable-project-upgrade
=> Disable project upgrade

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
MinorFriendsChanged was also called even when the event flag wasn't enabled?
=> DoFriendshipChangeEffects() fixes and cleanup

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp
After much finagling, Workboats can now enter the Ocean at compass like their promotion says.
Also speeds up calculations for "Terrain Passable with Tech" and "Feature Passable with Tech" Promotions in the general case.
=> Workboats in Ocean

(2) Vox Populi/Balance Changes/Text/en_US/UIText.sql, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Counts only one unique resource per city (doubled if monopoly), but now includes Strategic and Bonus resources.
=> Trade Route Resource Diversity Modifier Update

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp
Moved the check from CvCity to CvCityStrategy, so wonders will appear on the lists but won't be picked by the AI governor
=>  Fix to wonders disappearing from automated city lists

(3a) EUI Compatibility Files/LUA/UnitPanel.lua
Currently, if the name of a unit is edited the normal name of the unit still appears in parentheses, such as:
SCREAMING EAGLES (PARATROOPER)
This change makes it appear as:
SCREAMING EAGLES
This is the same change I make every time I download a new version
=> Remove default unit name when unit has custom name

(1) Community Patch/Core Files/Core Tables/CustomModOptions.xml, CvGameCoreDLL_Expansion2/CustomMods.cpp, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitCombat.cpp
MOD_CIVILIANS_RETREAT_WITH_MILITARY: Makes civilians units retreat with the military units when the latter gets heavy charged, could also affect the cases where the defending unit withdraws but haven't specifically checked for that. Separated this into a different modmod in case VP decides to implement this.
MOD_ATTRITION: Units take 5 damage per turn if they move in enemy lands, barbarian units, civilian units, scouts and submarines are immune. Also modifies heavy charge.
=> ATTRITION, CIVILIANS_RETREAT_WITH_MILITARY modmods

(2) Vox Populi/Balance Changes/Text/en_US/ReligionText.sql, CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp, CvGameCoreDLL_Expansion2/CvBeliefClasses.h, CvGameCoreDLL_Expansion2/CvCorporationClasses.cpp, CvGameCoreDLL_Expansion2/CvGameCoreUtils.cpp, CvGameCoreDLL_Expansion2/CvGameCoreUtils.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
Spend less time calculating, more time playing!
balance changes:
- Improvements that scale GEMS expend abilities + Transnationalism Franchises no longer need to be within workable distance of an owned city (still needs to be in owned territory and built by the player).
- The Holy Land reformation belief now works for any combination of 2 Holy Sites and Landmarks (instead of requiring exactly 2 Holy Sites or 2 Landmarks).
- Combat Strength PER UnitCombat modifiers from Promotions should now work for all Ranged Units.
=> Function Optimizations

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
CvPlayer::changeGoldenAgeTurns :
- iValue has only been used for Brazil's gain yields on golden age. Every passed parameter is the current turn's Golden Age Points.  This is a hidden exploit that gives you many more yields if you can trigger a golden age while currently overflowing in GAP.  I've changed it so that it only gives the current GA threshold in yields. The iValue parameter is now unnecessary.
- bug: if you gain a Golden Age that isn't free (eg the old Great Artist expend ability, or Spy Tech Steal when there are no techs to steal) while you are currently in a Golden Age, you don't cause the threshold to go up (ie. it's free).  FIXED
CvPlayer::getGoldenAgeLength :
CvGame::getGoldenAgeLength :
- now take a manual number of turns as an optional parameter to replace the default …
=> Golden Ages

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp
Fix for issue #8512 .
Explanation: It should be "or" instead of "and" in the if-clause: A trireme/lighthouse is buildable if the city is next to water (isCoastal(-1)) **and** the body of water is large enough (isCoastal(pkBuildingInfo->GetMinAreaSize()). The negated condition must use **or** then.
Additionally, for coastal units the check of GetMinAreaSize (10 for all ships, -1 for work boats) was missing, so ships could be build in any city next to water.
=> Prevent Triremes and Lighthouses in Lakes

(3a) EUI Compatibility Files/LUA/LoadScreen.lua, (3a) EUI Compatibility Files/LUA/LoadScreen.xml, (3a) EUI Compatibility Files/VP EUI Compatibility.civ5proj, Vox Populi Installer Files/CPPSetupData.iss, Vox Populi Installer Files/VPUI/FrontEnd/ContentSwitch.lua, Vox Populi Installer Files/VPUI/FrontEnd/ContentSwitch.xml, Vox Populi Installer Files/VPUI/FrontEnd/EULA.lua, Vox Populi Installer Files/VPUI/FrontEnd/FrontEnd.lua, Vox Populi Installer Files/VPUI/GameSetup/LoadScreen.lua, Vox Populi Installer Files/VPUI/GameSetup/LoadScreen.xml, Vox Populi Installer Files/VPUI/VPUI_0.Civ5Pkg, Vox Populi Installer Files/VPUI/VPUI_1.Civ5Pkg, Vox Populi Installer Files/VPUI/VPUI_2.Civ5Pkg
Adds VP tips to mod configuration pop-up and loading screen, for both EUI and nonEUI versions. Tips are stored in a table in the repurposed ContentSwitch.lua and can be expanded easily. This required dlc-type modding though, so I introduced a VPUI dlc mod, which also allows us to get rid of annoying EULA/Legal screens in the nonEUI versions. This can be used to add VP-specific options in the future. 
The modified EULA/Legal screen luas are taken from EUI, but the files were actually made by someone on civfanatics called Temudjin. The code isn't anything original though, basically sets a boolean to true and comments out a function, there is nothing problematic credits-wise, I've sent a message to Temudjin in any case.
Installer is modified accordingly, I compiled&tested it without errors.
=> Loading screen tips for VP

(2) Vox Populi/Core Files/CoreLua/WorldView.lua, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/CvUnitMission.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
I won't be able to mod for a while, but fundamentals are there and features are fully functional, only need some checks for edge cases & indicators on the UI. This is the most c++ intensive stuff I've ever done, so I'd appreciate if anyone could take a look at this, to see whether the code could be optimized better. I couldn't manage to use pointers or references for UnitIdContainer, maybe that's one area worth checking.
Linked Movement: Moves all units on the tile together, by calling DoLinkedMovement() on ALT+RCLICK. The function runs two loops, first a loop to get the movable units, their maximum and current movement points. The units are stored in a temporary vector for easier recall on the next loop. The second loop sets the units as IsLinked, and assigns the lowest max&current …
=> Linked & Group movement, DLL functions

CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvCultureClasses.cpp
- Moving the call of CvCityCulture::UpdateThemingBonusIndex() to low-level to catch all instances of when theming should be updated (fixes #8903).
- removed some redundancy
=> Update Theming in all situations

(2) Vox Populi/Core Files/CoreLua/WorldView.lua, (2) Vox Populi/LUA/UnitPanel.lua, (3a) EUI Compatibility Files/LUA/UnitPanel.lua, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
- Link icon will not show for ineligible units
- Aircraft can be rebased by right-clicking on a valid city
=> Link icon fix & RCLICK rebases aircraft

(2) Vox Populi/Core Files/CoreLua/ActionInfoPanel.lua, (2) Vox Populi/LUA/UnitPanel.lua, (3a) EUI Compatibility Files/LUA/UnitPanel.lua, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h
Shift clicking on the end turn button gives "skip mission" order to all idle units, this is also called when GetFirstReadyUnit() returns nil. I'm pretty sure that 99% cases of "can't progress turn" problems are due to that, this will provide a workaround while I take a look. May require clicking twice to take affect though.
On the link&group front, worker units will automatically be set as leaders because only leaders ask for orders. Group movement will check the destination plots and try to get close (ring1, ring2 etc.).
=> SHIFT+LCLICK Force Ends Turn, Final Tweaks to Linked&Group Movement

CvGameCoreDLL_Expansion2/CvTeam.cpp
Fix #8917 
Explanation: The case where no policy or no technology is required for a resource wasn't handled correctly. Since one of these conditions is always fulfilled, no resource notifications where shown at all. Compare also line 8171, where it was already correct (used there for updating plot yields and graphics).
=> Fix missing notifications for discovered resources

(2) Vox Populi/Vox Populi.civ5proj
They aren't packaged unless we add them to the project file. If they aren't included the map script crashes when generating a map.
=> Add new bonus resource files to mod project

(2) Vox Populi/Balance Changes/Leaders/Vanilla/VanillaLeaderChanges.sql, (2) Vox Populi/Balance Changes/Text/en_US/CivText.sql
Simply removes War Canoes promotion from Songhai land units, which gave them embarked sight and defense. I&People also wanted to take out the "attack from sea without penalty", but that would require splitting the Amphibious promotion, which would create some other annoyances.
=> Minor Songhai nerf

CvGameCoreDLL_Expansion2/CvCultureClasses.cpp, CvGameCoreDLL_Expansion2/CvCultureClasses.h, CvGameCoreDLL_Expansion2/CvGameQueries.cpp, CvGameCoreDLL_Expansion2/CvGameQueries.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvPlayerAI.h, CvGameCoreDLL_Expansion2/CvPlot.cpp
- Updates to AI considerations for when there exists a Civilization with a UI that functions with Antiquity Site Resources.
- AI won't consider local antiquity sites for digs if it can "connect" it with its own UI.
- Minor AI won't create archaeology dig quests for players who can't dig them up.
- AI considers local medieval antiquity sites to be worth keeping as landmarks.
=> Archaeology p1

(1) Community Patch/Core Files/Core Tables/CustomModOptions.xml, CvGameCoreDLL_Expansion2/CustomMods.cpp, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvUnit.cpp
Adds era scaling to GE & GM yields, active from renaissance and onwards. GE scales from base hurry (100 prod), GM scales with base gold + era gold, as GM needed a more hefty buff. Scalars are based on wonder production and investment cost.
=> Era scaling GE&GM yields modmod

(2) Vox Populi/Balance Changes/Text/en_US/UIText.xml, (2) Vox Populi/LUA/CityView.xml, (2) Vox Populi/LUA/CityView_small.xml, (3a) EUI Compatibility Files/LUA/CityView.xml, (3a) EUI Compatibility Files/LUA/CityView_small.xml
add key for 'Reset Specialists' : TXT_KEY_CITYVIEW_RESET_SPEC  
add key for 'Click here to have the governor reassign specialists.' : TXT_KEY_CITYVIEW_RESET_SPEC_TT
For English users, nothing changes.  
It allows me to translate into a foreign language.
=> make Reset Specialist Localizable

CvGameCoreDLL_Expansion2/CvGame.cpp
Hello! I did some MP debugging and looks like `getActivePlayer()` in `getSmallFakeRandNum()` causes a lot of desyncs across players because it differs on host and non-host player. With enabled logging it looks like (left - host; right - another one player): 
I'm not sure if `getStartYear()` is suitable here, point me if we should use something else.
=> getActivePlayer() in getSmallFakeRandNum() causes desyncs

CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Hello! I have several MP saves where CS triremes are stucking because when they are trying to move to neighboring plot, the pathfinder says them smth like "you are already here (because of TARGET_RING2 flag)", `MoveToTargetButDontEndTurn` returns `false` (because unit's plot wasn't changed) and they are trying again and again until timeout. Looks like it's 'ok' for SP because timeout is `10` for local games, but for MP it's `1000` and sometimes we have to wait 2-3 mins each turn again and again. 
I'm not sure whether such fix is ok overall but at least it resolves such situations.
=> Don't try to move if MOVEFLAG_APPROX_TARGET_RING2 already satisfied

CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp
AI workers should no longer remove and readd the same road tiles for shortcut roads.
AI workers will now build shortcut routes between cities which are not on the same landmass as the capital (and any other cities which do not have a direct road connection to the capital).
=> Fix AI logic for shortcut roads between non-capital cities

CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvAStar.h, CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp, CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.h, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Fixes some desyncs in #9864, description is [here](https://github.com/LoneGazebo/Community-Patch-DLL/issues/9864#issuecomment-1557527871).
Also improved logging a little bit in `CvBuilderTasking.cpp` and did minor cleanup.
=> Replace pointer with id if used as map key

(2) Vox Populi/Core Files/Overrides/EspionageOverview.lua, (2) Vox Populi/LUA/TradeLogic.lua, (3a) EUI Compatibility Files/LUA/TradeLogic.lua, CvGameCoreDLL_Expansion2/CvDealClasses.cpp
Fixed a bug in the new espionage system that the trade deals of other players were not shown correctly. While doing so, I discovered and fixed a much more serious bug that caused expired AI-AI trade deals to be renewed twice.
=> Fix trade deal bug

CvGameCoreDLL_Expansion2/CvCultureClasses.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPreGame.cpp
Ran [readability-container-size-empty](https://clang.llvm.org/extra/clang-tidy/checks/readability/container-size-empty.html). v90 build works after changing to /Zm260 similar to https://github.com/LoneGazebo/Community-Patch-DLL/commit/eab6a30633c6adb288283c9b9297b57ac69c2ed5#diff-2705f19fed026fce017b69e8eefea4a5df4610c4093feebe6e965e6057be40d4 and https://github.com/LoneGazebo/Community-Patch-DLL/pull/10739.
=> readability-container-size-empty

(3a) EUI Compatibility Files/LUA/UnitFlagManager.lua, CvGameCoreDLL_Expansion2/CvUnit.cpp
* Fix a bug where EUI unit flags could incorrectly show squad numbers for units created shortly after a unit in a squad dies
* Fix a bug where issuing squad move orders to a unit that just had a squad movement mission interrupted (either by user or by seeing enemy unit) would result in them continuing on their previous path
=> Squads modmod bugfixes

CvGameCoreDLLUtil/include/CvLuaMethodWrapper.h, CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp, CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h
Fix some issues causing the AI to love removing some existing improvements, especially on resources.
Increase value of already owned resources by a bit.
Add handling for GetXSameAdjacentMakesValid improvements, should help China to better plan their improvements.
Fix AI (way) overvaluing yields for X worked features from buildings and beliefs.
Make workers less focused on local improvements.
=> Builder AI fixes and tweaks

.github/workflows/cppcheck.yml
Cppcheck changed their tag versioning scheme. Fixes build for the CI. For squash and merge.
=> Fix cppcheck build

(4a) Squads for VP/UI/Squads.xml
Fixes a bug where the `SquadsEndMoveMode` option, when loading, ignored the user saved option and always loaded the default of "Alert on Arrival".
I don't know what caused this to change, but the way it used to work is the `RegisterCheckHandler()` event for the default radio button used to fire first, then the code that loaded the saved option value, which would call `SetCheck()` on the right one.
The way it works now is the opposite: first the option is loaded, then the default xml option is enabled, which triggers the check handler and overwrites it with the default.
The fix is to remove a default check value in the xml so that it no longer overwrites the user-loaded value. 
I had concerns that having no checked radio button in a radio button group would lead to undefined behavior, but …
=> Fix Squads Bug - Incorrectly Loading "Arrival Mode" user option

CvGameCoreDLL_Expansion2/TContainer.h
`m_items.erase(it->first)` invalidates `it`, causing `it->second` to read (potentially) freed data. The solution is just to erase from `m_order` before `m_items`.
=> Fix heap-use-after-free in TContainer::Remove

(2) Vox Populi/Database Changes/AI/LeaderFlavorSweeps.sql
A number of entries are increasing `FLAVOR_MOBILE` based on the civ having a skirmisher UU which is incorrect as it only covers melee cavalry/armor. This could cause the AI to play worse as it could focus on building too many melee cavalry rather than skirmishers.
Eventually, if `FLAVOR_SKIRMISHER` is supported then it would be good to add that to the appropriate civs.
=> Update LeaderFlavorSweeps.sql to remove flavor_mobile being used for skirmisher UUs

(1) Community Patch/Community Patch.civ5proj, (1) Community Patch/Kit/String/CPK.String.Distance.lua, (1) Community Patch/Kit/Util/CPK.Util.FuzzyTrie.lua
Adding some building blocks for better Civilopedia search:
* _CPK.String.Distance_ – Damerau–Levenshtein distance between two strings. Supports a max cutoff so we don’t waste time on strings that are too different.
* _CPK.Util.FuzzyTrie_ – Stub for a trie-based fuzzy search. Will let us store and look up phrases/words efficiently.
_P.S. Distance calculation is kinda hot. Right now it’s pure Lua, but we could speed it up a lot if we implement it in C++ and expose it to Lua._
=> CPK: Add string distance function and FuzzyTrie stub

(1) Community Patch/Core Files/VPUI/VPUI_core.lua, (1) Community Patch/LUA/Includes/TechButtonInclude.lua
Should fix https://github.com/LoneGazebo/Community-Patch-DLL/issues/11913
Cause: `VPUI` removed method that was used in other files
P.S. I have also the issue that `player.GetCivilizationBuilding` do not exist, but I think it requires building latest DLL instead of included one in repo.
=> Fix VPUI causing TechTree not loading

(3a) EUI Compatibility Files/ImprovedTechTree/TechTree.lua
The tech tree would not properly display [the icons for unlocked stuff]
- the call to `AddSmallButtonsToTechButton` was missing an argument
but still with that fixed the icons for buildings, improvements and units were missing...
- `GatherInfoAboutUniqueStuff( g_activeCivType )` in `TechButtonInclude.lua` needs to be called somewhere to fill the `ValidXXXBuilds` tables - I restored the call to the location it was before....
=> Two small fixes for TechTree.lua
