LoneGazebo/Community-Patch-DLL

Community Patch/Core Files/Core Changes/TextChanges.sql
Reverts LoneGazebo/Community-Patch-DLL#1054
=> Revert "Pedia Entry for Hidden antiguity sites"

Community Balance Patch/LUA/TechButtonInclude.lua
Fixed the issue in TechButtonInclude.lua to not cause a tech tree bug.
=> Critical Bug fix

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvGameCoreUtils.cpp, CvGameCoreDLL_Expansion2/CvGameCoreUtils.h, CvGameCoreDLL_Expansion2/CvInfos.cpp, CvGameCoreDLL_Expansion2/CvInfos.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitMovement.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaArea.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaArgsHandle.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaDeal.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaEnums.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaFractal.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaGame.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaGameInfo.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaLeague.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaMap.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaSupport.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaTeam.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaTeamTech.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
Also added a function Unit Class Instance per City.
Be sure that hovering units do not have a promotion for move all terrain. You'll add in whoward's mod for deep embarkation to the mod (unless you want hovering units to embark at coast). Also be sure that hovering units have all the embark abilities in UnitPromotions_UnitCombats such as PROMOTION_EMBARKATION, PROMOTION_DEFENSIVE_EMBARKATION, PROMOTION_ALLWATER_EMBARKATION. Those will be overridden in the DLL with deep embark, but they need to have that as a base.
=> changes to Hovering Units, corrected some itellisense stuff in lua

CvGameCoreDLLUtil/include/CvEnums.h, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvDealClasses.h, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyRequests.h, CvGameCoreDLL_Expansion2/CvDllGame.cpp, CvGameCoreDLL_Expansion2/CvDllGameDeals.cpp, CvGameCoreDLL_Expansion2/CvDllNetMessageHandler.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h, CvGameCoreDLL_Expansion2/CvNotifications.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp
...and perhaps some trade bug fixes (here's for hoping).
=> Incorporate changes for Active Diplomacy

Community Balance Patch/Modular Elements/Corporations/CorporationsOverview.lua, Community Balance Patch/Modular Elements/Corporations/CorporationsOverview.xml, Community Balance Patch/Modular Elements/Corporations/Text/en_US/CorpText.xml
Franchise functions now use IsFranchised() to power them.
Fixed some bad texts for the Corporations Overview.
All of my changes are developed using CBP only. I test with Community Patch + Community Balance Patch only. It is stable on my machine.
I will not test for other setups because there are too many changes. Especially with EUI, so I cannot guarantee that it will work flawless for those.
This is probably the root of other user's issues.
=> Some tweaks to the Corporation Overview

CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvTeam.h
See here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/1633
=> Fix to sell liberation exploit

CvGameCoreDLL_Expansion2/CvUnit.cpp
Tested. with and without option enabled.
=> Make sure all control paths return a value.

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvAIOperation.h
Problem: settler can be stuck in cities, waiting for an escort, but no unit are here, and the AI can't produce more, as he is in a big deficit (or maybe too much units, i added this in case of).
This fix the problem.
=> Don't wait an impossible escort.

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvContractClasses.cpp
=> bugfix in CvPlayerContracts::InitContractUnits

43 Civs CP/43 Civs CP/EUI/UnitPanel.lua, 43 Civs CP/43 Civs CP/No-EUI/UnitPanel.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/UnitPanel.lua, NoEUI Compatibility Files/Mod Template1/LUA/UnitPanel.lua
Reverts LoneGazebo/Community-Patch-DLL#3422
=> Revert "Update UnitPanel.lua"

CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyAI.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp
- Fixed missing division by 100 for yields from the PolicyGEorGM column.
=> PolicyGEorGM fix

CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp
- Building sanity check now considers experience modifiers.
=> Building Production AI now looks for experience modifier

43 Civs CP/43 Civs CP/EUI/CityView.xml, 43 Civs CP/43 Civs CP/EUI/CityView_small.xml, 43 Civs CP/43 Civs CP/EUI/EUI_tooltip_library.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CityView.xml, EUI Compatibility Files/EUI Compatibility Files/LUA/CityView_small.xml, EUI Compatibility Files/EUI Compatibility Files/LUA/EUI_tooltip_library.lua
1. CityView for big interface. 2. Culture tooltip properly displays Process.
=> 2 UI fixes

43 Civs CP/43 Civs CP/EUI/CityView.lua, 43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/43 Civs CP/EUI/EUI_tooltip_library.lua, 43 Civs CP/43 Civs CP/No-EUI/CivilopediaScreen.lua, CSD for CBP/Improvements/ImprovementText.xml, CSD for CBP/Promotions/Promotions.xml, Community Balance Patch/Balance Changes/Text/en_US/UIText.xml, Community Balance Patch/Balance Changes/Units/PromotionChanges.xml, Community Balance Patch/LUA/CivilopediaScreen.lua, Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp, EUI Compatibility Files/EUI Compatibility Files/LUA/CityView.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/EUI_tooltip_library.lua, NoEUI Compatibility Files/Mod Template1/LUA/CivilopediaScreen.lua
Tooltips fixes, Civilopedia promo categories
=> Tooltips fixes, Event MinorGiftUnit, Civilopedia promo categories

43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua
=> New event, #3894, Civilopedia

CSD for CBP/World Congress/IdeologyChanges.sql, CvGameCoreDLL_Expansion2/stackwalker/StackWalker.cpp
=> #3906 updated help

CvGameCoreDLL_Expansion2/CvCity.cpp
=> Fix for #3910

43 Civs CP/43 Civs CP/EUI/EUI_tooltip_library.lua, Community Balance Patch/Balance Changes/Text/en_US/UIText.xml, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaCity.h, EUI Compatibility Files/EUI Compatibility Files/LUA/EUI_tooltip_library.lua
#3910 fixed Yields from Trade Routes
=> #3910 fixed Yields from Trade Routes

43 Civs CP/43 Civs CP/EUI/EUI/EUI_text_en_us.xml
=> Missing texts for EUI/43civ

CvGameCoreDLL_Expansion2/CvPlayerAI.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.h, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
AI doesn't use siege units for pillage moves anymore
=> removed special rules concerning AI worker capture

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
Added hook calls for other yields (#3987)
=> Fixed event PlayerBullied (#3987)

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvGame.cpp
Reverts LoneGazebo/Community-Patch-DLL#4002
=> Revert "Fix for skipped turn on load in MP issue"

CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h
As it was such a simple fix I've done it for you! : )
Also exposed CvPlayer::GetDominationResistance to lua, hope you can include it.
=> Fixed Issue #4032 - Anti-warmonger fervour always zero

CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.h
stupid bug but quite severe ...
=> fix a recently introduced regression

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvAIOperation.h, CvGameCoreDLL_Expansion2/CvArmyAI.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp
path check before recruiting a unit
=> unbreak mixed land/sea ops

CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvArmyAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.h, CvGameCoreDLL_Expansion2/Lua/CvLuaGame.cpp
remove some useless code
fix a lua crash
=> improve tactical combat simulation in tight spaces

CvGameCoreDLL_Expansion2/CvDistanceMap.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.cpp
improve culture bomb plot selection
=> fix city distance map

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvEconomicAI.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.h
unified target check before removing units from tactical AI control
some additional sanity checks for military operations
=> fix a merge error (danger was not considered in combat simulation)

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, Community Patch/Core Files/Core Tables/CustomModOptions.xml, Community Patch/Core Files/Text/CoreText_en_US.xml
Undo stuff which got removed from what seems like merging errors.
=> Pius IX no 3

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLLUtil/include/CustomModsGlobal.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvImprovementClasses.h, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
Trait for a player unit to have a special unitclass upgrade that differs from the normal upgrade path.
=> Fix a crash in CvPolicyClasses.cpp

CvGameCoreDLL_Expansion2/Lua/CvLuaGame.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaGame.h
Game.IsPitbossHost
Game.IsHost
Game.GetTimeStringForYear
I wanted these for a mod mod that deals with the generating AutoSave Events.
=> Exposed a few simple funcs in LuaGame

CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGame.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Related to discussion at https://github.com/LoneGazebo/Community-Patch-DLL/pull/4002.
Seem to be a slightly better positioning for the fix than before.
=> Improving the turn skip fix a bit

Community Balance Patch/Modular Elements/ArchaeologistUIMods/GlobalArchaeologistDigSites.lua
Added check if proper tech is researched.
=> Fix for #4164

43 Civs CP/43 Civs CP/EUI/EUI/EUI_text_en_us.xml, 43 Civs CP/43 Civs CP/EUI/EUI_tooltip_library.lua, EUI Compatibility Files/EUI Compatibility Files/EUI/EUI_text_en_us.xml, EUI Compatibility Files/EUI Compatibility Files/LUA/EUI_tooltip_library.lua
Tooltip info for GRANTED BY building (EUI only)
=> Changes for #4332

43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/43 Civs CP/No-EUI/CivilopediaScreen.lua, Community Balance Patch/LUA/CivilopediaScreen.lua, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua, NoEUI Compatibility Files/Mod Template1/LUA/CivilopediaScreen.lua
=> Iamblichos

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
- Added IsCapitalOnly column to Traits. Currently only affects Trait_YieldChangesPerImprovementBuilt.
@Hokath Do you want to experiment with the changes now? I can send you a compiled DLL.
=> Franklin Roosevelt 30/5/2018

Community Patch/Core Files/PNM Mods DB/API/UnifiedYields.xml, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
- Trait counterpart for Building_SeaPlotYieldChanges.
=> Tojo 3/6/2018

CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h
=> Flanking bonus promo fix

Community Balance Patch/Balance Changes/Text/en_US/ReligionText.sql, Community Patch/Core Files/Core Changes/CoreChanges.sql
1. Unit SelectionSound
cf.
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4807
-----
2. Syncretism
missing Production
>Syncretism gains +1p per 2 followers of other religions
=> fixed typos (11/9)

43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/43 Civs CP/No-EUI/CivilopediaScreen.lua, Community Balance Patch/LUA/CivilopediaScreen.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua, NoEUI Compatibility Files/Mod Template1/LUA/CivilopediaScreen.lua
New fields added to Civilopedia screens
=> New fields added to Civilopedia screens

Community Balance Patch/Balance Changes/Text/en_US/BuildingText.sql, Community Patch/Core Files/Text/CoreText_en_US.xml
=> Fix for #4924

CvGameCoreDLL_Expansion2/CvPlot.cpp
=> Fix for #4892

CvGameCoreDLL_Expansion2/CvBarbarians.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
=> rewrite jumpToNearestValidPlot() for good

43 Civs CP/43 Civs CP/EUI/CSD/CSDCompatibility.sql, 43 Civs CP/43 Civs CP/EUI/MilitaryOverview.xml, 43 Civs CP/43 Civs CP/No-EUI/CSD/CSDCompatibility.sql, 43 Civs CP/43 Civs CP/No-EUI/MilitaryOverview.xml, Community Balance Patch/Balance Changes/Text/en_US/UIText.sql, Community Balance Patch/LUA/MilitaryOverview.xml, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.h, EUI Compatibility Files/EUI Compatibility Files/CSD/CSDCompatibility.sql, EUI Compatibility Files/EUI Compatibility Files/LUA/MilitaryOverview.xml, NoEUI Compatibility Files/Mod Template1/CSD/CSDCompatibility.sql, NoEUI Compatibility Files/Mod Template1/LUA/MilitaryOverview.xml
Altered CvPlot methods: constructor, destructor, reset, calculateYieldFast, getYieldWithBuild, read, and write.
changeYield is added, with a m_aiArbitraryYields array that keeps of changes.
The method is exposed to lua as pPlot:ChangeYield(YieldType, iChange)
=> change yield

Community Patch/Core Files/PNM Mods DB/API/UnifiedYields.xml, CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvBuildingClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
- Great Person progress in the city when a building is constructed. Bonus only granted if the constructed building at least the same era as the stated era.
- Fixed instant great person progress tooltip which are processed per turned not working.
=> Victoria 24/02/2019

CvGameCoreDLL_Expansion2/CvPlayerAI.cpp
- Update check for pseudo Great Artists to include new GAP mechanic.
Save game compatible.
=> Pius IX 20/03/2019

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
- Added Trait_NonSpecialistFoodChange (changes the food consumed by each non-specialist citizen).
=> Ekeuhnick 14/04/19

43 Civs CP/43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/43 Civs CP/No-EUI/CivilopediaScreen.lua, Civilization IV Diplomatic Features - CP/Build/(1a) Civilization IV Diplomatic Features - CP Only/LUA/CivilopediaScreen.lua, Civilization IV Diplomatic Features - CP/Civilization IV Diplomatic Features - CP/LUA/CivilopediaScreen.lua, Community Balance Patch/LUA/CivilopediaScreen.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CivilopediaScreen.lua, NoEUI Compatibility Files/Mod Template1/LUA/CivilopediaScreen.lua
- Civilopedia now works correctly with standalone unique buildings.
Save game compatible.
=> Meiji 21/04/2019

CvGameCoreDLL_Expansion2/CvAIOperation.cpp, CvGameCoreDLL_Expansion2/CvAIOperation.h, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvSiteEvaluationClasses.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTechClasses.cpp
remove unnecessary info from logs
=> fixes for bully operations, embarked unit movement etc

Community Balance Patch/Balance Changes/AI/Flavors/LeaderFlavors.sql, Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Fixed a small imbalance in the AI's calculation of opinion ranges, so that favorable and unfavorable opinions are now on an equal scale, which also brings it in line with its usage as +/- % in the approach calculation.
[Current Ranges]
150+: Unforgivable
70 to 149: Enemy
20 to 69: Competitor
-20 to 19: Neutral
-70 to -21: Favorable
-150 to -71: Friend
-151 or lower: Ally
[Fixed Ranges]
150+: Unforgivable
70 to 149: Enemy
20 to 69: Competitor
-19 to 19: Neutral
-69 to -20: Favorable
-149 to -70: Friend
-150 or lower: Ally
Fixed a bug in the DoEstimateOtherPlayerOpinions function which seems to set all positive opinions to FAVORABLE rather than using the weight properly and brought it in line with the fix above.
Fixed a few issues relating to opinion value clearing when war is declared:
- …
=> Minor AI Fixes

CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyAI.cpp
- Wonder cost increase from having wonders was not working correctly.
- AI not acquiring policies after dropping below super unhappy threshold, as they were granted free tenets even though they cannot ideologies yet.
#5385 
#5386
=> Bugfixes 20/05/19

(3) CSD for CBP/Buildings/CSDBuildings.xml
Added Nuke Immunity to diplomatic national wonders, so they are the same as other national wonders
=> NukeImmune Change

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitProductionAI.cpp
- Added Trait_NoBuilds, which allows you to block certain builds for certain a civ. Trait_BuildsUnitClasses will override it.
=> Trait_NoBuilds 07/07/19

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Fix an issue where requesting that the AI move their troops set the military promise flag for the wrong player
Remove global penalty from breaking a military promise for teammates
AI will get the same penalty as humans for ignoring a military promise
=> Military Promise Fixes

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
=> Fix Sign Typo

Community Balance Patch/Balance Changes/Text/en_US/CivText.sql, Community Patch/Core Files/PNM Mods DB/DIPLO/AIWarmongerAdjustments.xml, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
(Recreated because old pull request got bugged or something)
Fix warmongering opinion penalty applying to unmet players
Removed certain negative diplo mods for teammates
Fix prioritization for traitor opinion
Fix issue where AI zeroes out war weight towards their own vassal regardless of circumstances (could prevent them from winning the game)
Highlight Venice's UA drawback in red text (to match India's description)
Typo fixes
=> Small Fixes

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h
- Added Trait_DomainProductionModifiersPerSpecialist.
- Trait_SpecialistYieldChanges now considered for SetIsSmaller and SetIsNerd.
=> Frederick 24/09/19

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDangerPlots.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/CvUnitCombat.cpp, CvGameCoreDLL_Expansion2/CvUnitCombat.h, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
be less greedy when recruiting units for attacking city
=> clean up damage calculation code

Community Balance Patch/Modular Elements/Corporations/Text/en_US/CorpText.xml
=> Typo Fixes

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Shouldn't be factoring in grand strategy so early in the game. :)
=> Fix excessive early game DoFs

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Should address many of the issues raised in this beta test (AI should be significantly less bloodthirsty :) ).
=> Diplo Fixes & Improvements

CvGameCoreDLL_Expansion2/CvGameCoreUtils.h, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp
fix barb spawning
improve performance
=> fix aborted AI ops

CvGameCoreDLL_Expansion2/CvTechClasses.cpp, CvGameCoreDLL_Expansion2/CvTechClasses.h
- Replaced int data types with long long, hopefully fixing the tech overflow issue.
See issue #5878.
=> TechCostOverflowFix 23/11/19

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvGameCoreUtils.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
@ilteroi As you can see from the open pull request, your changes to DoMakeWarOnPlayer conflicted with my own changes to that function (to make the diplo AI able to make opportunity strikes on City-States), and were not merged into the master branch.
I copied over your changes so they'd be compatible without any merge errors, so you can merge this into master and then the master branch into Ole. :)
If your latest build is from the master branch you may want to update it, since it won't have your fixes to DoMakeWarOnPlayer. 
If it's from the Ole branch you may also want to update it, since it won't have my diplo fixes re: City-States.
(It's of course possible you merged it manually, I don't know :) )
Also, while it's minor, I made a change to one of the CBP files (Balance Changes > AI > …
=> Merge compatibility with Ole & fix early game aggression bug

(4) Civ IV Diplomatic Features - CBP/SQL/Globals.sql, Civilization IV Diplomatic Features - CP/Build/(1a) Civilization IV Diplomatic Features - CP Only/SQL/Globals.sql, Civilization IV Diplomatic Features - CP/Civilization IV Diplomatic Features - CP/SQL/Globals.sql, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Reverts LoneGazebo/Community-Patch-DLL#5886
doesn't build
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2181	illegal else without matching if	VoxPopuli	D:\sources\civ-vp\CvGameCoreDLL_Expansion2\CvDiplomacyAI.cpp	6201	
Error	C2039	'SetTurnIdeologyswitch' : is not a member of 'CvPlayerCulture'	VoxPopuli	D:\sources\civ-vp\CvGameCoreDLL_Expansion2\CvDiplomacyAI.cpp	24943	
Error	C2065	'eMyPlayer' : undeclared identifier	VoxPopuli	D:\sources\civ-vp\CvGameCoreDLL_Expansion2\CvPlayer.cpp	9798
=> Revert "Diplo Fixes & Improvements"

(4) Civ IV Diplomatic Features - CBP/SQL/Globals.sql, (7c) Leugi's Israel for VP/XML/Text/DavidSpeech.xml, Civilization IV Diplomatic Features - CP/Build/(1a) Civilization IV Diplomatic Features - CP Only/SQL/Globals.sql, Civilization IV Diplomatic Features - CP/Civilization IV Diplomatic Features - CP/SQL/Globals.sql, Community Balance Patch/Balance Changes/Text/en_US/UnitText.xml, Community Patch/Core Files/Text/CoreText_en_US.sql, Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp
@pineappledan I noticed a few typos in your Israel dialogue :)
@ilteroi If you're hotfixing, please merge :) - the non-DLL changes can be ignored for the hotfix
@LoneGazebo See #5813
=> Fix typos & small issues

Community Patch/Core Files/Text/CoreText_en_US.sql, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Sorry for all the pull requests today :)
=> Additional text fixes

CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
Fixed build error from #5915. Also fixed variable name and equal sign placement to satisfy my OCD.
=> Minor Fixes

Community Patch/Core Files/Core Changes/DiploOpinionWeights.sql, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Just a few small miscellaneous fixes.
=> Small fixes & add more religion/ideology weight

CvGameCoreDLL_Expansion2/CvMap.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.cpp
extend GetPlotsAtRange() function for larger ranges
=> fix some minor issues in new combat sim

Community Patch/Core Files/Core Tables/CustomModOptions.xml, CvGameCoreDLL_Expansion2/CustomMods.cpp, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
- Enable for compiling main VP build.
- Now to use CustomModOptions.xml to enable instead.
=> BattleRoyale 04/01/20

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Fix excessive DP & DoF formation
Fix an issue with backstabbing penalties for vassals
=> Fix some diplo bugs

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvCity.cpp
- Siphon production now checks if the production of the unit/building/project is complete, then creates the unit/building/project properly.
=> Jose Rizal 06/01/20

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp
- Fixed bug with open border bonus applying when trading with yourself.
- Fixed bug with siphon being able to produce multiple copies of the same building.
- Units and buildings produced from the siphon trait should now behave exactly the same as when produced normally.
- Added some validity checks for siphoning.
- Production siphoning should now work better with unique buildings.
=> Jose Rizal 07/01/20

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h
- Trade production siphon now no longer gives the city overflow production.
- Siphon now checks for mutually exclusive buildings.
=> Jose Rizal 08/01/20

(3) CSD for CBP/World Congress/IdeologyChanges.sql, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Now free of any adjustments to warmongering penalties. :)
=> Some diplo adjustments

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvTeam.cpp
For the hotfix, mostly performance-related.
=> Savegame compatible fixes for diplo AI

CvGameCoreDLL_Expansion2/CvPlayer.cpp
=> fix Zealotry still giving up to 50% more strategics

43 Civs CP/43 Civs CP/CP Only/ProductionPopup.lua, 43 Civs CP/43 Civs CP/EUI/CityView.lua, 43 Civs CP/43 Civs CP/No-EUI/ProductionPopup.lua, Community Patch/LUA/ProductionPopup.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CityView.lua, NoEUI Compatibility Files/Mod Template1/LUA/ProductionPopup.lua
- UI lua edits to allow mod to work.
=> FaithBuildingsInPuppets 01/02/20

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, ISSUE_TEMPLATE
Will fix for the version after this, but for now this will do.
Also makes AI more likely to value long-term friendships.
=> Fix buggy diplo mods & some adjustments

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvPolicyAI.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.h
- Added new columns ExtraMissionaryStrength and ExtraMissionarySpreads to Policies.
- Added new table Policy_YieldChangesPerReligion (works similiarly to Building_YieldChangesPerReligion).
=> Misc 16/02/20

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
AI expands more slowly and modifier is worse, so put the threshold a bit higher
(will adjust again based on feedback from next version, if needed)
=> Adjustment to reckless expander modifier

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h
Code doesn't currently build, still needs work.
=> Rewrite approach selection functions

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
*grumbles in self-directed annoyance*
=> Fix for revised function build errors

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h
Tested, saved and loaded, ran a few turns, no crashes. Approach updating seems to be working as well.
=> Add serialized approach values array

43 Civs CP/43 Civs CP/CP Only/ProductionPopup.lua, 43 Civs CP/43 Civs CP/EUI/CityView.lua, 43 Civs CP/43 Civs CP/No-EUI/ProductionPopup.lua, Community Patch/LUA/ProductionPopup.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/CityView.lua, NoEUI Compatibility Files/Mod Template1/LUA/ProductionPopup.lua
- UI lua edits to allow mod to work. Previously did not get merged into VP.
=> FaithBuildingsInPuppets 07/03/20

Community Patch/Core Files/Core Changes/DiploApproachWeights.sql, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
There shouldn't be any build errors in this, but I don't have time to check - just numbers tweaking.
=> Raise AI aggression level, esp. in earlygame

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvBuildingClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp
- Added column ResourceQuantityToPlace to Building_ResourcePlotsToPlace.
- Building_ResourcePlotsToPlace no longer uses ResourceQuantityToPlace in Buildings.
=> Misc 12/03/20

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp
=> Diplo Code Cleanup

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
I hate fixing the spacing bugs from conflict markers. :)
=> prevent merge error with ole branch

43 Civs CP/43 Civs CP/EUI/CSD/Compatibility_en_US.sql, 43 Civs CP/43 Civs CP/No-EUI/CSD/Compatibility_en_US.sql, Community Balance Patch/Balance Changes/Text/en_US/TextChanges.sql, EUI Compatibility Files/EUI Compatibility Files/CSD/CompatibilityText/Compatibility_en_US.sql, NoEUI Compatibility Files/Mod Template1/CSD/CompatibilityText/Compatibility_en_US.sql
**Missed specifying this valid location**
=> Some Typo Fixes

Community Balance Patch/Modular Elements/TradeUIMod/GlobalCityStatesGifts.xml, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h
=> Add captured capital/holy city memory values to diplo AI

43 Civs CP/43 Civs CP/43 Civs CP.civ5proj, 43 Civs CP/43 Civs CP/CP Only/WonderPopup.xml, 43 Civs CP/43 Civs CP/EUI/WonderPopup.xml, 43 Civs CP/43 Civs CP/No-EUI/WonderPopup.xml, Community Balance Patch/Community Balance Patch.civ5proj, Community Balance Patch/LUA/WonderPopup.xml, Community Patch/Community Patch.civ5proj, Community Patch/LUA/WonderPopup.xml, EUI Compatibility Files/EUI Compatibility Files/CBP Compatibility Files.civ5proj, EUI Compatibility Files/EUI Compatibility Files/LUA/WonderPopup.xml, NoEUI Compatibility Files/Mod Template1/LUA/WonderPopup.xml, NoEUI Compatibility Files/Mod Template1/No-EUI CBP Compatibility.civ5proj
I don't know how to compile it, but theoretically should work, just test it first to be sure. 
It's a fix for #5592
=>  Check First If It Works, Fix Wonder Popup Text Overflow 

Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h
@LoneGazebo Nothing of great substance in this PR, so don't worry about it affecting testing/stability/etc.
=> Few small improvements (+ a typo fix)

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Based on feedback on the forums that the AI was too passive and didn't evaluate humans properly.
=> Adjustments to AI aggression & military strength estimations

Community Balance Patch/Balance Changes/Text/en_US/PolicyText.sql, Community Balance Patch/Balance Changes/Text/en_US/UnitText.xml, Community Balance Patch/Balance Changes/Units/PromotionChanges.xml
=> Recursive Self-Improvement

EUI Compatibility Files/EUI Compatibility Files/LUA/AssignStartingPlots.lua, NoEUI Compatibility Files/Mod Template1/LUA/AssignStartingPlots.lua
- Backend code for Even More Resources mod.
- No changes if mod not activated.
- Adding unrelated mod stuff here to avoid conflicts, due to how AssignStartingPlots.lua requires overrides to be modded.
=> EvenMoreResources 19/10/20

CvGameCoreDLL_Expansion2/CvPlayer.cpp
This is for pineappledan's Spain rework: https://forums.civfanatics.com/threads/10-07-spain-rework.663564/
=> Fix GetFreeUnitOnConquest to set the religion of religious units

Community Patch/Mapscripts/Communitu_79a.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/AssignStartingPlots.lua, NoEUI Compatibility Files/Mod Template1/LUA/AssignStartingPlots.lua
All maps:
- Slightly more coal and less aluminum
- Civs less likely to start completely isolated
=> AssignStartingPlots and Communitu_79a update

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaGame.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
@LoneGazebo (Probably) fixed the bug preventing resurrected players from becoming vassals. I would test if it weren't for the CTD bugs - but pretty confident it's fixed. Would be good to have this in the next hotfix. :)
Savegame compatible.
=> Clean up DoLiberatePlayer & fix #6992 & fix merge error

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvEconomicAI.cpp, CvGameCoreDLL_Expansion2/CvEconomicAI.h, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvProcessProductionAI.cpp, CvGameCoreDLL_Expansion2/CvUnitProductionAI.cpp
removed "crazy" economic strategies because they never triggered
removed weird pre-bully check
=> add GetPlayerWhoStoleMyFavoriteCitySite()

CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp
- Fixed crash when conquering capitals as Rome, or when MOD_BUILDINGS_THOROUGH_PREREQUISITES is enabled.
=> RSI 19/01/20

Community Patch/Mapscripts/Communitu_79a.lua
-   More hills in deserts
- Flat desert plot has a chance to become hills if adjacent to other flat desert plots. The chance increases with more adjacent flat desert.
-   Lower amount of aluminum
=> Communitu_79a v2.2.0

CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvAStar.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
finish building improvements before tactical AI if possible and safe
try to add a safeguard against a crash
=> add extra parameters for IsPlotConnectedToPlot

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
=> conscript only land units

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.h
@LoneGazebo I am now done :)
(for now anyway haha)
=> Fix all the warmongering penalty code

43 Civs CP/43 Civs CP/CP Only/LeaderHeadRoot.lua, 43 Civs CP/43 Civs CP/EUI/LeaderHeadRoot.lua, 43 Civs CP/43 Civs CP/EUI/NotificationPanel.lua, 43 Civs CP/43 Civs CP/No-EUI/LeaderHeadRoot.lua, Community Balance Patch/LUA/LeaderHeadRoot.lua, Community Patch/LUA/LeaderHeadRoot.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/LeaderHeadRoot.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/NotificationPanel.lua, NoEUI Compatibility Files/Mod Template1/LUA/LeaderHeadRoot.lua
=> Fix missing "then"s

CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
- Negative values for a proposal due to it blocking the opposite proposal are now only considered when evaluating for yourself. (Prevents weird decisions to yea proposals which negatively affect you but also all your enemies)
- Proposal Allocation values now considered globally so they will match up directly with how a civ votes.
- many small value tweaks
=> WC changes

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
AI now makes roads to nearby CS allies
=> Clean up some of the horrible DoContactMinorCivs() code

CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
- ALIGNMENT_WAR now only chosen if player actually wants to war the target
=> Small Alignment change

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvBuildingClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvUnitClasses.cpp, CvGameCoreDLL_Expansion2/CvUnitClasses.h
Reverts LoneGazebo/Community-Patch-DLL#7765
=> Revert "Add Building_YieldChangeWorldWonder and Unit  CostScalerNumRepeats"

CvGameCoreDLLUtil/include/CvString.h
I really hope nothing depended on this broken behavior
=> Fix CvString::IsEmpty() subscripting this

CvGameCoreDLL_Expansion2/CvCityCitizens.cpp
remove worst specialist actually removes the worst specialist
=> simplify yield weight logic

CvGameCoreDLL_Expansion2/CvUnit.cpp
Oops. Multiplayer is working though.
=> Fix multiplayer never trying to sync CvUnit

CvGameCoreDLL_Expansion2/CvPlot.cpp
- Fixed potential crash in CvPlot::isCoastalLand (null Area pointer).
=> Misc 28/05/21

CvGameCoreDLL_Expansion2/CvUnitClasses.h
=> Remove erroneous single quote

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h, CvGameCoreDLL_Expansion2/CvTreasury.cpp, CvGameCoreDLL_Expansion2/CvTreasury.h, CvGameCoreDLL_Expansion2/CvUnitProductionAI.cpp, CvGameCoreDLL_Expansion2/CvUnitProductionAI.h
- CvPlayerTraits
- CvTreasury
- CvUnitProductionAI
Also remove several unused members in CvCity
=> Clean-up more serialization in autovariables branch

CvGameCoreDLL_Expansion2/CvBeliefClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.h
compute plot combo bonus effects only on demand
fix two forgotten instances of pass-by-value
=> fix venice building investment

CvGameCoreDLL_Expansion2/CvDllDatabaseUtility.cpp
Fixes #8015 and probably a lot of other unreported issues
Edit - ~~Probably~~ fixes #8009 and ~~_maybe_~~ fixes #8011
=> Load mod options before database caches

CvGameCoreDLL_Expansion2/CvPreGame.cpp
=> Minor clean-ups in PreGame

CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp
- FreePolicy column in PolicyBranchTypes now works correctly with ideology branches.
=> Bugfixes 20/06/21

CvGameCoreDLL_Expansion2/CvPlayer.cpp
- Fixed possible crash in CvPlayer::UpdateAreaEffectUnits.
=> Misc 20/06/21

43 Civs CP/43 Civs CP/AssignStartingPlots.lua, EUI Compatibility Files/EUI Compatibility Files/LUA/AssignStartingPlots.lua, NoEUI Compatibility Files/Mod Template1/LUA/AssignStartingPlots.lua
- Compatibility for running in modpack mode.
=> EvenMoreResources 20/06/21

Community Patch/Core Files/Core Tables/CoreTableEntries.sql, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.h
(from InkAxis)
Also fixed a bug I noticed- liberating a city was reducing war weariness by 75% rather than the intended 25%.
=> Add ExperienceAllUnitsFromLiberation; liberation yields only fire once

CvGameCoreDLL_Expansion2/CvPolicyAI.cpp, CvGameCoreDLL_Expansion2/CvPolicyAI.h
=> Don't make AI try to finish incompletable policy branches.

Community Patch/Core Files/Core Tables/CoreTableAdditions.xml, CvGameCoreDLL_Expansion2/CvCorporationClasses.cpp, CvGameCoreDLL_Expansion2/CvCorporationClasses.h, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.h
The policy gives a franchise for every X of the improvement you own, not increasing the cap.
=> Add Policy_FranchisePerImprovement

43 Civs CP/43 Civs CP/AssignStartingPlots.lua, NoEUI Compatibility Files/Mod Template1/LUA/AssignStartingPlots.lua
=> add mountain and snow biases for non-EUI and 43-civ versions

Community Balance Patch/Modular Elements/Corporations/Corporations.xml, Community Balance Patch/Modular Elements/Corporations/Text/en_US/CorpText.xml, Community Patch/Core Files/Core Tables/CoreTableEntries.sql, Corporations/Corporations/Buildings/Corporations.xml, Corporations/Corporations/Text/en_US/CorpText.xml, CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvBuildingClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.h, CvGameCoreDLL_Expansion2/Lua/CvLuaGame.cpp
EnhancePantheon now has option to not set the religion as enhanced.
Instant Religious Pressure added to buildings.
=> Corp text cleanup and lua EnhancePantheon improvement

Community Patch/Core Files/Core Tables/CoreTableEntries.sql
=> Fix missing line

CvGameCoreDLL_Expansion2/CvTeam.cpp
- Fixed resources not being revealed correctly when its reveal technology has completed researching.
=> Bugfixes 15/08/21

CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp
Improved after fixing some issues with it. @LoneGazebo
=> Block non-founder AIs from building Hagia Sophia, Borobudur, St. Basil (version 2.0)

CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.h
- I made a change so that the host must propose first before the other civs can propose resolutions. I did a poll to see what people think and most agreed though not unanimous: 
https://forums.civfanatics.com/threads/poll-give-host-the-first-congress-proposal.672180/
Can just revert the commit if you don't want it though as it doesn't affect any other changes.
- Changed some values in CvGameDeals::GetDealValueWithPlayer( as open borders and defensive pacts were being valued very highly.
- Other changes were mostly to just proposal scoring and a change to how votes are distributed after being scored.
=> More world congress changes

Community Patch/Core Files/Text/CoreText_en_US.sql, Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Fix AI "most valuable ally" evaluation
Fix some other bugs with DP selection
Fix bug with IsActHostileTowardsHuman() usage
Fix text key bug with new debug mode info
Fix Great Generals promotion help text
=> RSI Fixes & Improvements

CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.h
=> Add IsLiberator() function for cleaner references & make some tweaks

CvGameCoreDLL_Expansion2/CvTacticalAI.cpp, CvGameCoreDLL_Expansion2/CvTacticalAI.h
army units retreat if they fail to gather
=> tweak AI behavior towards barbarians

CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp, CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.h, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp
avoid putting GPTI next to a border
=> disband missionaries with the wrong religion

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp
Revert "Update isUnderSiege for diplo AI's peace willingness purposes (due to ilteroi's changes)"
This reverts commit 202304fb784df51d691e5e507c6bd91170818625.
=> Revert to old isUnderSiege logic

CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp
Two main changes are: 
- Making the 'What Would Make This Deal Work?' button work and give the simplest but also best (for human) deal that would be acceptable.
- AI to AI deals are now equalised on both sides, this will be a big change so requires some proper testing but thought you might want to look at it @RecursiveVision ? Since it will affect Diplomacy a lot.
=> Deal System Update

CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvEconomicAI.cpp
Implements late investment. New rules, both for the player and the AI, are:
- Investment is possible as long as there is more than 1 turn remaining
- When investing after >= 50% complete, production overflow from investment is capped at one production-per-turn
AI considers investing in the buildings  with fewer turns remaining as more expensive, applies to buildings already in construction and new entries both.
+20% expensive at 4 turns, +50% at 3 turns, +100% at 2 turns remaining. 
This is done by increasing the gold cost input given to CanWithdrawMoneyForPurchase function, but it doesn't affect the actual amount of gold deduced from the treasury. I've conducted a few 300 turn tests and was able to get statistically significant results showing that this indeed makes the AI less likely to …
=> Late investment feature

CvGameCoreDLL_Expansion2/CvUnit.cpp
I'm guessing these were typos, reverting them to a few versions earlier fixes Dojo.
=> Fix for Dojo yields

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
A minus sign snuck in and made India's satellite cities take negative pressure.
=> India Convert Hotfix

CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayer.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h, EUI Compatibility Files/EUI/NeededText.xml, EUI Compatibility Files/LUA/TopPanel.lua
fixes #8370 and better shows Misc resources in UI
=> Improve Resource UI, add in GP Resources

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
@ilteroi
RecomputeFollowers() has been added after AddReligiousPressure().  There's no point in recomputing twice in succession.
=> RecomputeFollowers() 

43 Civs CP/EUI/CSD/Compatibility_en_US.sql, 43 Civs CP/No-EUI/CSD/Compatibility_en_US.sql, Community Balance Overhaul/Balance Changes/Text/en_US/ReligionText.sql, EUI Compatibility Files/CSD/CompatibilityText/Compatibility_en_US.sql, NoEUI Compatibility Files/CSD/CompatibilityText/Compatibility_en_US.sql
=> Organize ReligionText.sql

Community Patch/Mapscripts/Communitu_79a.lua
=> Communitu_79a v2.3.1

CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.h
Try it out!  I've made sure that Founding a religion and Conquering a holy city update everything properly.
Pantheons are automatically disqualified because they don't have a holy city.
Your accessor is GetOwnedReligion()
=> GetOwnedReligion() Update

CvGameCoreDLL_Expansion2/CvMilitaryAI.cpp
Silly mistake, sorry bout that
=> Spotted a typo in my last commit

CvGameCoreDLL_Expansion2/CvUnitProductionAI.cpp
Minor tweak to UnitProductionAI, reducing UU spam for recons (e.g. bandeirantes)
=> Less spam for recon UUs

CvGameCoreDLL_Expansion2/CvHomelandAI.cpp
- Units were being duplicated as they were getting upgraded twice (my bad)
=> Unit Upgrade Bugfix

43 Civs CP/43 Civs Community Patch.civ5proj, 43 Civs CP/EUI/StackedPromotionIcons/StackedPromotionIcons.sql, 43 Civs CP/EUI/UnitPanel.lua, 43 Civs CP/EUI/UnitPanel.xml, 43 Civs CP/EUI/UnitPanel_small.xml, EUI Compatibility Files/LUA/UnitPanel.lua, EUI Compatibility Files/LUA/UnitPanel.xml, EUI Compatibility Files/LUA/UnitPanel_small.xml, EUI Compatibility Files/StackedPromotionIcons/StackedPromotionIcons.sql, EUI Compatibility Files/VP EUI Compatibility.civ5proj
Adds stacked promotion icons feature from [Promotion Flags for VP](https://forums.civfanatics.com/threads/promotion-flags-eui-for-vp.651957/). Also allows the promotion row to be scrolled horizontally.
=> UnitPanel features

Community Balance Overhaul/Balance Changes/Text/en_US/BuildingText.sql
Corrected bomb shelter (strategic defense system) text
=> Corrected bomb shelter (strategic defense system) text

Community Patch/Core Files/CoreLua/EnemyUnitPanel.lua
Bonus in the enemy section was appearing at the wrong time. Also, it was calling a variable not yet created.
=> EUPanel Enemy Mounted

Community Balance Overhaul/Balance Changes/Text/en_US/PromotionText.sql, Community Balance Overhaul/Balance Changes/Text/en_US/UnitText.xml
UnitText.xml broke with a previous update.
=> Language_en_US fix

CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
I can't test this but I think it should work
=> ResolutionVoteOpinionDetails fix

CvGameCoreDLL_Expansion2/CvDllDatabaseUtility.cpp
Technically fixes #8639 I'm still not certain whether or not this test is useful. I think it's better to at least have it working so that those more involved in the database can determine whether or not they think this is useful since it'll be logging properly at least.
=> fix ID column test

Community Patch/Mapscripts/Communitu_79a.lua
revert 2.3.1 changes since plot:IsLake doesn't work
new lake logic to ensure lakes don't leak to the polar seas
This fixes #8653 and hopefully doesn't generate new bugs
=> Communitu_79a v2.3.3

Community Balance Overhaul/Balance Changes/Leaders/GodsKings/GKLeaderChanges.sql, Community Balance Overhaul/Balance Changes/Leaders/LeaderStartBiases.sql, Community Balance Overhaul/Balance Changes/Leaders/Vanilla/VanillaLeaderChanges.sql
massively reduce the amount of them to help those who REALLY need it
=> change start biases

Community Patch/Core Files/Text/CoreText_en_US.sql
Inform the populi about alt click
=> Add ALT + CLICK to queue help

Community Patch/Core Files/Core Tables/CustomModOptions.xml
It seems I forgot to add this when I made the dll change months ago
=> Add LOCAL_GENERALS_NEAREST_CITY to CustomModOptions

CvGameCoreDLL_Expansion2/CvUnit.cpp
=> fix promotion duration increasing every time the promotion is gained

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
=> fix decreasing yields from CS

43 Civs CP/EUI/CivilopediaScreen.lua, 43 Civs CP/No-EUI/CivilopediaScreen.lua, Civilization IV Diplomatic Features - CP/Civilization IV Diplomatic Features - CP/LUA/CivilopediaScreen.lua, Community Balance Overhaul/LUA/CivilopediaScreen.lua, EUI Compatibility Files/LUA/CivilopediaScreen.lua, NoEUI Compatibility Files/LUA/CivilopediaScreen.lua
Civilopedia building entries now link properly to all relevant required and future buildings.
Addresses #8667.
Library
Papermaker
Independence Hall
Hoover Dam
Piazza San Marco
Rialto District
=> Civilopedia Buildings Links

Community Balance Overhaul/Balance Changes/Text/en_US/PromotionText.sql, Community Balance Overhaul/Balance Changes/Text/en_US/UnitText.xml, Community Balance Overhaul/Balance Changes/Units/UniqueUnits.sql
Removed duplicate Promotion from Denmark UA; standardized Free Pillage text.
=> Free Pillage Text Updates

CvGameCoreDLL_Expansion2/VoxPopuli.vcxproj
@RecursiveVision Second attempt of https://github.com/LoneGazebo/Community-Patch-DLL/pull/8758. Lack of sleep. Please let me know if it works.
=> Disable project upgrade

CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp
try assigning some booleans initially. That should help.
=> Workboats in Ocean

(2) Vox Populi/Vox Populi.civ5proj
An oversight on my part, we should block these just to be safe
=> Added merged submods to Blocks list

(1) Community Patch/Core Files/Core Tables/CustomModOptions.xml
=> Added AI_UNIT_PRODUCTION entry to CustomModOptions.xml

(2) Vox Populi/Core Files/CoreLua/PuppetCityPopup.lua, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp
@RecursiveVision check the MinorCivAI bit as you said you made some changes to unit gifting.
=> OCC Popup + other changes

(1) Community Patch/Core Files/Core Tables/CustomModOptions.xml, CvGameCoreDLL_Expansion2/CustomMods.cpp, CvGameCoreDLL_Expansion2/CustomMods.h, CvGameCoreDLL_Expansion2/CvPlot.cpp
=> MOD_ADJACENT_BLOCKADE : Allow land units to blockade undefended adjacent tiles

(2) Vox Populi/Balance Changes/Text/en_US/CivText.sql
Had the civilopedia entry
https://github.com/LoneGazebo/Community-Patch-DLL/issues/8832
=> Fix Brazilwood help text

(2) Vox Populi/Balance Changes/Leaders/CivStartBiases.sql
Reorganized start biases and gave justifications.
```
Civilization  Bias
Spain         ~~Any~~ Coast
Mongolia      Grassland/Plains
Shoshone      Plains/Grassland
Huns          Plains/Grassland
Poland        Avoid Jungle/Forest
Rome          Hills
```
Please comment here with any disagreements and why.
=> Start Biases

CvGameCoreDLL_Expansion2/CvUnit.cpp
Aircraft don't have BaseCombat, but do have a BaseRangedCombat. They should start with one attack.
Fixes #8879.
=> Aircraft need Attacks

Vox Populi Installer Files/CPPSetupData.iss
The installer sometimes cannot get the correct path for EUI and this has been one of the most common issues with the new players. I added a new page asking for the Civ 5 path only when installing EUI versions of VP. Users could have gotten confused when selecting the subdirectory (Assets\DLC), so the installer asks for base Civ 5 path instead, then appends Assets\DLC by itself. Works fine on my end, making a PR if anyone wants to review.
=> Make the installer ask for CIV path when installing EUI versions

CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h
=> NoFollowup in Neutral Territory

(1) Community Patch/Core Files/CoreLua/EventChoicePopup.lua, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
Fixes issue where two events that shared choices would only allow you to select one.
=> Event Choices specify Event Types

CvGameCoreDLL_Expansion2/CvUnit.cpp
=> Submarines can no longer attack Cities in CP

CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp
=> Medical Lab cannot be sold

(2) Vox Populi/Balance Changes/Policies/Piety/Piety.sql
=> Burghers Golden Age Production

Vox Populi Installer Files/VPUI/FrontEnd/ContentSwitch.lua, Vox Populi Installer Files/VPUI/FrontEnd/ContentSwitch.xml
https://github.com/LoneGazebo/Community-Patch-DLL/issues/9021
=> Mod configuration box scales automatically with the size of the tip

(1) Community Patch/(1) Community Patch (v 108).modinfo, (1) Community Patch/Core Files/Text/CoreText_en_US.xml, (1) Community Patch/LUA/CityStateStatusHelper.lua, (2) Vox Populi/(2) Vox Populi (v 15).modinfo, (2) Vox Populi/LUA/CityStateStatusHelper.lua, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvPlot.h
Fix for #8850 and #9028 .
Quest to acquire a city modified for OCC games.
=> Modify conquer city quest for OCC games

(2) Vox Populi/Balance Changes/Ideologies/Order/OrderChanges.sql
=> Five Year Plan Mines/Quarries

CvGameCoreDLLUtil/include/CvDllInterfaces.h, CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvDealAI.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyRequests.cpp, CvGameCoreDLL_Expansion2/CvDllContext.cpp, CvGameCoreDLL_Expansion2/CvDllPreGame.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGlobals.cpp, CvGameCoreDLL_Expansion2/CvGlobals.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvNotifications.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvStartPositioner.h, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitCombat.cpp, CvGameCoreDLL_Expansion2/CvUnitMission.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
=> eliminate undefined behavior caused by ICvUnknown::operator delete

CvGameCoreDLL_Expansion2/CvAStar.cpp, CvGameCoreDLL_Expansion2/CvAStar.h, CvGameCoreDLL_Expansion2/CvGameCoreUtils.cpp, CvGameCoreDLL_Expansion2/CvMap.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, FirePlace/include/FireWorks/FFastList.h
Fixes for issues found during Linux porting.
=> Fix various issues

CvGameCoreDLL_Expansion2/CvPlot.cpp
moving the hook allows lua modders to modify resources/improvements on the tile before calculations about the tile are made.
=> Move TileOwnershipChanged hook and cleanup

(2) Vox Populi/Balance Changes/Terrain/NewFarmResources.sql, (2) Vox Populi/Balance Changes/Terrain/NewFarmResources_Text.xml, (2) Vox Populi/Core Files/CoreLua/AssignStartingPlots.lua, (2) Vox Populi/Mapscripts/Communitu_79a.lua
Communitu_79a v2.4.0
also remove rice's help text
=> balance wheat, rice and maize spawns

(2) Vox Populi/Core Files/CoreLua/AssignStartingPlots.lua
Halves strategics when reduced supply is active
=> Addes StartPlots support for Reduced Supply modmod

CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp, CvGameCoreDLL_Expansion2/CvBuildingClasses.h, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp, CvGameCoreDLL_Expansion2/CvCorporationClasses.cpp, CvGameCoreDLL_Expansion2/CvDangerPlots.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvDllCity.cpp, CvGameCoreDLL_Expansion2/CvGame.cpp, CvGameCoreDLL_Expansion2/CvGameCoreDLLPCH.h, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlayerAI.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvTacticalAnalysisMap.cpp, CvGameCoreDLL_Expansion2/CvTeam.cpp, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnitClasses.cpp, CvGameCoreDLL_Expansion2/CvUnitClasses.h
Needs review and stability testing.
=> Use `nullptr` for `NULL` when building with Clang and fix errors.

CvGameCoreDLL_Expansion2/CvUnit.cpp
Fixed some stupid mistakes, added town scaling and took out the flat era gold bonus.
=> Fixed GP Era Scaling modmod

(1) Community Patch/Core Files/Text/CoreText_en_US.xml, CvGameCoreDLL_Expansion2/CvEspionageClasses.cpp
Make TT for ID/Kill chances more accurate
=> Small tweak to espionage

(2) Vox Populi/Balance Changes/Text/en_US/ReligionText.sql
=> Fix overlapping text issue

CvGameCoreDLL_Expansion2/CvTeam.cpp
Reverts LoneGazebo/Community-Patch-DLL#9227
=> Revert "addPlayers() should do an isAlive() check before adding players"

(2) Vox Populi/Balance Changes/Espionage/PrimaryEspionageEvents.xml
=> Remove Level Requirements for Counterspy Missions

(2) Vox Populi/Modular Elements/TradeUIMod/UITradeRoutesEnhancements.xml
=> fix: Fix display of Faith generation from a Trade Route in Trade Overview

(2) Vox Populi/Database Changes/Espionage/SpyPassiveBonuses.xml, CvGameCoreDLL_Expansion2/CvPlot.cpp
=> Fix spy surveillance bug

CvGameCoreDLL_Expansion2/CvPolicyAI.cpp
=> Fix Community Patch CTD

(1) Community Patch/Core Files/CoreLua/EnemyUnitPanel.lua, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
=> Fix enemy unit panel melee from plot estimation

(1) Community Patch/Core Files/Core Tables/CustomModOptions.xml, (2) Vox Populi/Core Files/Overrides/WorldView.lua, CvGameCoreDLL_Expansion2/CustomMods.cpp, CvGameCoreDLL_Expansion2/CustomMods.h, Vox Populi Installer Files/UI_bc1/Core/Highlights.xml
* Adds the `ROUTE_PLANNER` customModOption
* Forwards `RButtonDown` and `RButtonUp` events in `INTERFACEMODE_ROUTE_PLANNER_DRAW` interface mode via LUA event
* Creates Route Planner EUI Highlight Style Definitions
=> route planner modmod pre-requisites

CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp
Searching before insertion is not necessary. vs and clang builds work.
=> cppcheck stlFindInsert

(1) Community Patch/Community Patch.civ5proj, (1) Community Patch/Core Files/CoreLua/EnemyUnitPanel_small.xml
=> Fix incorrect combat panel layout

CvGameCoreDLL_Expansion2/CvPlayer.cpp
=> Fix crash (10908)

(2) Vox Populi/Core Files/Overrides/EspionageOverview.lua
=> Fix replacement spies not being able to move (#11000)

CvGameCoreDLL_Expansion2/CvEconomicAI.cpp
=> Fix crash when starting in later eras

(1) Community Patch/(1) Community Patch (v 138).modinfo
=> Update modinfo file

CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp
Fix #11395
Fix #11396 
Fix #11397 
Fix #11398
=> Fix 4.17 crashes

CvGameCoreDLL_Expansion2/CvWorldBuilderMapLoader.cpp
=> Fix clang build error

(1) Community Patch/Database Changes/Defines/CoreDefineChanges.sql, (3a) EUI Compatibility Files/ImprovedTopPanel/TopPanel.lua, (3a) EUI Compatibility Files/LUA/CityBannerManager.lua, (3a) EUI Compatibility Files/LUA/PlotHelpManager.lua, CvGameCoreDLL_Expansion2/CvCity.cpp, CvGameCoreDLL_Expansion2/CvCity.h, CvGameCoreDLL_Expansion2/CvCityCitizens.cpp, CvGameCoreDLL_Expansion2/CvDealClasses.cpp, CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp, CvGameCoreDLL_Expansion2/CvEspionageClasses.cpp, CvGameCoreDLL_Expansion2/CvHomelandAI.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/CvPlayer.cpp, CvGameCoreDLL_Expansion2/CvPlot.cpp, CvGameCoreDLL_Expansion2/CvReligionClasses.cpp, CvGameCoreDLL_Expansion2/CvTradeClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTypes.cpp, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvVotingClasses.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
- Fix asserts
- Fix Chartered Company giving extra resources only within working range
=> Fix asserts

CvGameCoreDLL_Expansion2/CvImprovementClasses.cpp, CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaPlot.cpp
=> Fix improvement crash

.github/workflows/cppcheck.yml
=> cppcheck-2.17.1

(1) Community Patch/Database Changes/Civilizations/TraitTableChanges.sql, CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.cpp, CvGameCoreDLL_Expansion2/CvTraitClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp
Great artists start the Golden Age with research points equal to half the median of all currently researchable technologies.
=> Traits:ArtistGoldenAgeTechBoost

(1) Community Patch/Core Files/Overrides/EnemyUnitPanel.lua, (1) Community Patch/Database Changes/Text/en_US/UI/CoreNewUIText.xml, CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp, CvGameCoreDLL_Expansion2/CvPromotionClasses.h, CvGameCoreDLL_Expansion2/CvUnit.cpp, CvGameCoreDLL_Expansion2/CvUnit.h, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp, CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h
Implement cs bonus from city state marriages
=> 4UC integration: MarriageMod/MarriageModCap UnitPromotions Columns

CvGameCoreDLL_Expansion2/CvDealAI.cpp
Found this issue while debugging some weird crashes during my experiments.
=> Fixed a crash when the plot has no resource.

(2) Vox Populi/Database Changes/Text/en_US/Civilizations/NewCivilizationText.xml, (2) Vox Populi/Database Changes/Text/en_US/UnitPromotions/NewPromotionText.xml
Riachuelo appears twice (copy-paste error)
Nilometer comes from a scenario so its description already existed, needs replace instead of row (or to update in the .sql)
=> Errors in text merge

(2) Vox Populi/INSTRUCTIONS.txt, (3a) EUI Compatibility Files/INSTRUCTIONS.txt, (3b) 43 Civs Community Patch/MANUAL INSTALL.txt, Opener.rtf, VPSetupData.iss
Add uninstall option
More detailed 'missing DLC' error message
Don't delete LUA folders in VP non-EUI
=> Autoinstaller updates

.github/workflows/build_vp.yml, .github/workflows/cppcheck.yml, build_vp_clang_sdk.py
Add GitHub Action annotations
Inspiration from https://github.com/TheSuperHackers/GeneralsGameCode/blob/main/.github/workflows/ci.yml
=> Enhance CI workflow

CvGameCoreDLL_Expansion2/CvTacticalAI.h
Fix https://github.com/LoneGazebo/Community-Patch-DLL/issues/11986
=> Fix RTC1 cast failure in CvTacticalPlot::changeDamage

CvGameCoreDLL_Expansion2/CvGame.cpp
Add ASSERT so we can debug UI access violation.
=> Add ASSERTs for UI interface
